// System codes → friendly labels, and which systems the box-art route can source. Shared by the
// browse page and the navbar filter panel, which used to keep divergent copies of the same map.
export const SYSTEM_LABEL = {
  nes: "NES", snes: "SNES", genesis: "Genesis", gb: "Game Boy", gbc: "Game Boy Color",
  gba: "Game Boy Advance", n64: "Nintendo 64", gc: "GameCube", wii: "Wii", ps1: "PlayStation", ps2: "PlayStation 2", arcade: "Arcade",
  psp: "PSP", dc: "Dreamcast", naomi: "Naomi", atomiswave: "Atomiswave", saturn: "Saturn",
  sms: "Master System", gg: "Game Gear", sg1000: "SG-1000", segacd: "Sega CD",
  sega32x: "32X", pce: "TurboGrafx-16", ngpc: "Neo Geo Pocket", wsc: "WonderSwan Color",
  a2600: "Atari 2600", a7800: "Atari 7800", lynx: "Atari Lynx", vb: "Virtual Boy",
  fds: "Famicom Disk System", neogeo: "Neo Geo", "3do": "3DO",
  cdi: "CD-i", coleco: "ColecoVision", intv: "Intellivision", vectrex: "Vectrex",
  o2em: "Odyssey²", channelf: "Channel F", arcadia: "Arcadia 2001",
  pokemini: "Pokémon Mini", supervision: "Supervision", scummvm: "ScummVM",
  nds: "Nintendo DS", "3ds": "Nintendo 3DS",
  // Heavy lane (Moonlight-streamed, docs/arcade-heavy-lane-plan.md §7.1).
  switch: "Switch", ps3: "PlayStation 3", ps4: "PlayStation 4", wiiu: "Wii U", x360: "Xbox 360",
  pc: "PC",
  // Capture lane (H5): a browser room for a heavy title shows system "capture" in its descriptor.
  capture: "Live",
};

export const systemLabel = (s) => SYSTEM_LABEL[s] || (s ? s.toUpperCase() : "");

// Console tiles for the browse page's system carousel: a brand-coloured panel carrying the console's
// wordmark and a photo of the hardware. They are BUILT ASSETS, committed under assets/consoles and
// generated by scripts/console-art/build-console-art.py from Wikimedia Commons sources (credits in
// that folder's ATTRIBUTION.md) — nothing is fetched at runtime, and a system with no tile simply has
// none rather than falling back to a broken image.
//
// The eager glob is what makes that safe: Vite resolves every file in the folder at build time, so a
// newly-added tile is picked up by rebuilding and a MISSING one is `undefined` here rather than a 404
// in the browser. (A template-string import path would defeat the bundler and break in production.)
const CONSOLE_TILES = import.meta.glob("../../assets/consoles/*.webp", {
  eager: true, query: "?url", import: "default",
});

const TILE_BY_SYSTEM = Object.fromEntries(
  Object.entries(CONSOLE_TILES).map(([path, url]) => [path.split("/").pop().replace(/\.webp$/, ""), url]),
);

/** The tile image for a system code, or undefined when we have no art for it. */
export const consoleTile = (system) => TILE_BY_SYSTEM[String(system || "").toLowerCase()];

// When the hardware itself first went on sale, ANYWHERE — Famicom 1983 rather than NES 1985, Mega
// Drive 1988 rather than Genesis 1989. That is what makes the shelf read as a timeline instead of a
// popularity chart: scrolling right walks backwards through console generations, which is an order
// you can navigate from memory even when you can't name the machine you're looking for.
//
// ISO strings so they sort as plain text — no Date parsing, no timezone to get wrong.
//
// Two entries are judgement calls, because they aren't consoles:
//   arcade  — 1971, Computer Space, the first coin-op video game. The platform genuinely predates
//             every console here, so it lands at the very end of the shelf despite being one of the
//             largest collections.
//   scummvm — 1987, Maniac Mansion: the first SCUMM game, which is what the engine is named after.
// `pc` and `capture` are deliberately absent — see EVERGREEN_SYSTEMS below.
export const SYSTEM_RELEASED = {
  switch: "2017-03-03", ps4: "2013-11-15", wiiu: "2012-11-18", "3ds": "2011-02-26",
  wii: "2006-11-19", ps3: "2006-11-11", x360: "2005-11-22",
  psp: "2004-12-12", nds: "2004-11-21", atomiswave: "2003-02-01",
  pokemini: "2001-12-14", gc: "2001-09-14", gba: "2001-03-21",
  wsc: "2000-12-09", ps2: "2000-03-04", ngpc: "1999-03-19",
  dc: "1998-11-27", naomi: "1998-11-20", gbc: "1998-10-21",
  n64: "1996-06-23", vb: "1995-07-21", ps1: "1994-12-03",
  saturn: "1994-11-22", sega32x: "1994-11-21", "3do": "1993-10-04",
  supervision: "1992-01-01", segacd: "1991-12-12", cdi: "1991-12-03",
  snes: "1990-11-21", gg: "1990-10-06", neogeo: "1990-04-26",
  lynx: "1989-09-01", gb: "1989-04-21", genesis: "1988-10-29",
  pce: "1987-10-30", scummvm: "1987-10-05", a7800: "1986-05-01",
  fds: "1986-02-21", sms: "1985-10-20", nes: "1983-07-15",
  sg1000: "1983-07-15", vectrex: "1982-11-01", coleco: "1982-08-01",
  arcadia: "1982-05-01", intv: "1979-12-03",
  o2em: "1978-12-01", a2600: "1977-09-11", channelf: "1976-11-01",
  arcade: "1971-11-15",
};

// Platforms that never had A release date because they never stopped having one. The PC is not a
// 1981 machine we emulate, it is the current one — what this lane streams is whatever runs today —
// and `capture` is the live window-capture lane, newer still. Dating them by their oldest ancestor
// (the IBM PC) would bury the newest thing on the shelf down among the Ataris, so they head it
// instead, and claim no year on their tiles.
export const EVERGREEN_SYSTEMS = new Set(["pc", "capture"]);

/** The release year to show on a tile, or "" for the platforms that have no honest one. */
export const systemYear = (system) => (SYSTEM_RELEASED[String(system || "").toLowerCase()] || "").slice(0, 4);

/**
 * Newest first, so scrolling right goes back in time: evergreen platforms, then hardware by release
 * date. A system we have no date for sorts to the END rather than the front — an unknown is not a new
 * console, and a newly-ingested platform should not silently take pride of place on the shelf until
 * someone gives it a date above.
 */
export function byConsoleAge(a, b) {
  const ea = EVERGREEN_SYSTEMS.has(a);
  const eb = EVERGREEN_SYSTEMS.has(b);
  if (ea !== eb) return ea ? -1 : 1;
  const da = SYSTEM_RELEASED[a] || "";
  const db = SYSTEM_RELEASED[b] || "";
  if (da && db && da !== db) return da < db ? 1 : -1;
  if (da !== db) return da ? -1 : 1;
  return systemLabel(a).localeCompare(systemLabel(b));
}

// Systems the box-art route can source (libretro-thumbnails) — so a card requests /ArcadeImage even
// before its art is cached (the route lazily fetches on first view). Naomi/atomiswave are skipped
// (arcade-named art won't match → don't 404 those cards). Mirror of ArcadeBoxArt.ThumbRepo keys.
export const ART_SYSTEMS = new Set([
  "nes", "snes", "genesis", "gb", "gbc", "gba", "n64", "gc", "wii", "ps1", "ps2",
  "psp", "dc", "sms", "gg", "sg1000", "segacd", "sega32x", "pce", "ngpc", "wsc",
  "a2600", "a7800", "lynx", "vb", "fds", "nds", "3ds",
  // arcade/neogeo now resolve real titles → art via libretro (neogeo) or IGDB cover (arcade).
  "arcade", "neogeo",
]);

/** True when a card should attempt /ArcadeImage rather than going straight to its placeholder. */
export const canHaveArt = (game) => Boolean(game?.hasBoxArt) || ART_SYSTEMS.has(game?.system);

// Heavy/capture lane: a native app streamed by Moonlight or the capture worker, with no libretro core
// and no CloudRetro save path at all (docs/arcade-heavy-lane-plan.md §7.1). `pc` belongs here too —
// every pc row in the catalog carries Lane="heavy" — and being in this set is what correctly denies it
// Continue/Quickload, since a captured native app has no emulator state to serialize.
export const HEAVY_LANE_SYSTEMS = new Set(["switch", "ps3", "ps4", "wiiu", "x360", "pc", "capture"]);

// Systems with NO emulator save-state: their progress is their own save data, not a serialized
// machine state. psp is a noSaveStates core (config.worker-gl.yaml — a t=106 there returns
// ErrNoSaveStates). Keep in step with that file.
//
// ⚠ ps2 was in this set from 2026-07-22 to 2026-08-01 and should NOT be re-added. It was never a core
// that cannot serialize — patch 0030 added working Save/Load for it, and people used it. It was
// flagged noSaveStates to stop the periodic autosave minting states nothing booted from, which took
// the manual buttons with it. The config now uses noAutoSaveStates for that, so only the timer is
// affected and ps2 has save-states like any other core. The distinction being drawn here is "this
// core CANNOT be serialized", not "we would rather it didn't serialize on a schedule".
//
// scummvm is here for a DIFFERENT reason and is not marked in that config: the core simply cannot
// serialize. Observed live 2026-07-27 —
//   Libretro save on quit failed error="retro_serialize_size returned 0 (core cannot save-state this game)"
// so Save/Load/Continue silently do nothing there. It degraded correctly by accident (no save rows are
// ever written, so the launch modal already fell through to Clean Start), but the in-room Save button
// was still offered and would fail silently. ScummVM's progress is entirely its own in-game save,
// written through ScummVM's savepath.
//
// These have no state to continue from or quickload, so the launch modal collapses to Clean Start
// alone for them — and, happily, they can never be save-scummed either: their own save system is
// legitimate exactly the way a real memory card is.
export const NO_SAVE_STATE_SYSTEMS = new Set(["psp", "scummvm", ...HEAVY_LANE_SYSTEMS]);

/** True when a system can offer Continue / Quickload at all (i.e. it has emulator save-states). */
export const hasSaveStates = (system) => !NO_SAVE_STATE_SYSTEMS.has(String(system || "").toLowerCase());

// The fixed quicksave slot (SaveStore.QuickSlot). Deliberately NOT slot 0 — that belongs to the
// autosave / save-on-quit "Continue" state, so pressing Save can never overwrite it.
export const QUICK_SLOT = 99;
