// <auto-generated> by scripts/books/gen/gen_entities.py from docs/books/v2-mapping.json — do not edit by hand.
#nullable enable
using System;

namespace MovieTheater.Books.Db
{
    // books.db — the runtime's only file.
    /// <summary>A scanned root (comics / books; Calibre-managed or not)</summary>
    public sealed class LibraryRoot
    {
        public int Id { get; set; }
        public string Path { get; set; } = "";
        public ItemKind Kind { get; set; }
        public bool IsCalibre { get; set; }
        public bool Enabled { get; set; }
    }

    /// <summary>Folder tree (ids preserved); aggregates folded in; TopFolderId = the v1 'collection'</summary>
    public sealed class Folder
    {
        public int Id { get; set; }
        public int RootId { get; set; }
        public int? ParentId { get; set; }
        public ItemKind Kind { get; set; }
        public string Path { get; set; } = "";
        public string? Name { get; set; }
        public string? NormalizedName { get; set; }
        public int Depth { get; set; }
        public int? TopFolderId { get; set; }
        public int DirectChildCount { get; set; }
        public int DescendantItemCount { get; set; }
        public DateTime? FolderModifiedAt { get; set; }
        public DateTime? IndexedAt { get; set; }
        public bool HasIcon { get; set; }
    }

    /// <summary>Normalized publisher (ids preserved)</summary>
    public sealed class Publisher
    {
        public int Id { get; set; }
        public string Name { get; set; } = "";
        public string? FullName { get; set; }
    }

    /// <summary>One file = one item (ids preserved = Comics.Id). File identity + the browse-hot flags + the materialized Resolved* scalars. THE browse projection joins Item + Series only.</summary>
    public sealed class Item
    {
        public int Id { get; set; }
        public int RootId { get; set; }
        public int FolderId { get; set; }
        public int? TopFolderId { get; set; }
        public ItemKind Kind { get; set; }
        public string Path { get; set; } = "";
        public string FileName { get; set; } = "";
        public string? Extension { get; set; }
        public ContainerFormat ContainerFormat { get; set; }
        public long FileSize { get; set; }
        public DateTime? FileModifiedAt { get; set; }
        public DateTime? IndexedAt { get; set; }
        public int? PageCount { get; set; }
        public string? Title { get; set; }
        public string? NormalizedTitle { get; set; }
        public int? CalibreBookId { get; set; }
        public int? PublisherId { get; set; }
        public int? SeriesId { get; set; }
        public bool IsExcluded { get; set; }
        public bool KeepInDirectory { get; set; }
        public double? CoverAspect { get; set; }
        public string? ResolvedTitle { get; set; }
        public string? ResolvedSeries { get; set; }
        public string? ResolvedPublisher { get; set; }
        public int? ResolvedYear { get; set; }
        public int? ResolvedMonth { get; set; }
        public DatePrecision ResolvedDatePrecision { get; set; }
        public int? ResolvedRating { get; set; }
        public SynopsisSource ResolvedSynopsisSource { get; set; }
        public string? ResolvedCreatorsCsv { get; set; }
        public string? ResolvedTagsCsv { get; set; }
        public DateTime? ResolvedAt { get; set; }
        public Series? Series { get; set; }
        public Folder? Folder { get; set; }
        public Publisher? Publisher { get; set; }
        public ItemState? State { get; set; }
        public ItemSignature? Signature { get; set; }
        public ComicEmbedded? Embedded { get; set; }
        public BookDetail? Book { get; set; }
        public ComicDetail? Comic { get; set; }
    }

    /// <summary>Churny per-item state rewritten by jobs (health, thumbnail, cover dims, exclusion detail) so the catalog row is not rewritten</summary>
    public sealed class ItemState
    {
        public int ItemId { get; set; }
        public bool IsBroken { get; set; }
        public string? BrokenReason { get; set; }
        public DateTime? BrokenCheckedAt { get; set; }
        public string? ThumbnailError { get; set; }
        public DateTime? ThumbnailCheckedAt { get; set; }
        public int? CoverWidth { get; set; }
        public int? CoverHeight { get; set; }
        public string? CoverDimsComputedFor { get; set; }
        public string? ExclusionReason { get; set; }
        public DateTime? ExcludedAt { get; set; }
    }

    /// <summary>Dedup signatures (comics only)</summary>
    public sealed class ItemSignature
    {
        public int ItemId { get; set; }
        public string? ContentFingerprint { get; set; }
        public long? CoverPHash { get; set; }
        public string? PageSignature { get; set; }
        public string? SignaturesComputedFor { get; set; }
    }

    /// <summary>Raw ComicInfo.xml as read from the archive (comics with a ComicInfo; never rewritten - CVDB-resolved names go to ItemTag/ItemCredit)</summary>
    public sealed class ComicEmbedded
    {
        public int ItemId { get; set; }
        public string? Series { get; set; }
        public string? Number { get; set; }
        public string? AltSeries { get; set; }
        public string? AltNumber { get; set; }
        public int? Volume { get; set; }
        public string? Title { get; set; }
        public string? Summary { get; set; }
        public string? Publisher { get; set; }
        public string? Imprint { get; set; }
        public string? Genre { get; set; }
        public string? Tags { get; set; }
        public string? Characters { get; set; }
        public string? Teams { get; set; }
        public string? Locations { get; set; }
        public string? StoryArc { get; set; }
        public string? Web { get; set; }
        public string? Language { get; set; }
        public string? Format { get; set; }
        public string? PublicationDate { get; set; }
        public string? Writers { get; set; }
        public string? Pencillers { get; set; }
        public string? Inker { get; set; }
        public string? Colorist { get; set; }
        public string? Letterer { get; set; }
        public string? CoverArtist { get; set; }
        public string? Editor { get; set; }
        public bool? BlackAndWhite { get; set; }
        public string? Manga { get; set; }
        public int? Rating { get; set; }
        public string? Identifier { get; set; }
        public string? Notes { get; set; }
        public int? Count { get; set; }
        public string? AgeRating { get; set; }
    }

    /// <summary>Calibre-native identity of a book (authors -> ItemCredit, subject tags -> ItemTag)</summary>
    public sealed class BookDetail
    {
        public int ItemId { get; set; }
        public string? Isbn { get; set; }
        public string? SeriesName { get; set; }
        public double? SeriesIndex { get; set; }
        public string? Publisher { get; set; }
        public string? PublishedOn { get; set; }
        public string? Language { get; set; }
        public string? Description { get; set; }
    }

    /// <summary>Parse-pipeline output (comics only). ParsedSeriesKey is the resolution INPUT; SeriesId on Item is DERIVED from it</summary>
    public sealed class ComicDetail
    {
        public int ItemId { get; set; }
        public string? ParsedSeriesKey { get; set; }
        public string? IssueNo { get; set; }
        public int? Year { get; set; }
        public int? VolumeNo { get; set; }
        public string? Publisher { get; set; }
        public ComicFormat Format { get; set; }
        public string? FormatRaw { get; set; }
        public bool IsCollection { get; set; }
        public string? EventName { get; set; }
        public string? IssueTitle { get; set; }
        public Confidence Confidence { get; set; }
        public ParseSource SeriesSource { get; set; }
        public ParseSource IssueSource { get; set; }
        public ParseSource YearSource { get; set; }
        public ParseSource PublisherSource { get; set; }
        public string? FolderSeries { get; set; }
        public int? FolderYear { get; set; }
        public string? ParseNotes { get; set; }
        public DateTime? ParsedAt { get; set; }
    }

    /// <summary>DERIVED canonical series (ids preserved) + the series-scoped facts every issue used to carry; rebuilt by books-resolve-series from ComicDetail.ParsedSeriesKey + SeriesKeyLink</summary>
    public sealed class Series
    {
        public int Id { get; set; }
        public string? ParsedKey { get; set; }
        public string CanonicalKey { get; set; } = "";
        public string? Name { get; set; }
        public string? DisplayNameOverride { get; set; }
        public int IssueCount { get; set; }
        public int? YearStart { get; set; }
        public int? YearEnd { get; set; }
        public bool IsOngoing { get; set; }
        public string? Franchise { get; set; }
        public int? PublisherId { get; set; }
        public int? CvVolumeId { get; set; }
        public int? ExternalWorkId { get; set; }
        public long? MuSeriesId { get; set; }
        public SynopsisSource ResolvedSynopsisSource { get; set; }
        public int? ResolvedRating { get; set; }
        public DateTime? ResolvedAt { get; set; }
    }

    /// <summary>Every parsed spelling -> its canonical Series (DERIVED)</summary>
    public sealed class SeriesAlias
    {
        public string ParsedKey { get; set; } = "";
        public int SeriesId { get; set; }
    }

    /// <summary>Old-id redirect for merged series (all 44,261 v1 rows carried; ?series=<oldId> resolves through it)</summary>
    public sealed class SeriesMerge
    {
        public int OldSeriesId { get; set; }
        public int? NewSeriesId { get; set; }
        public DateTime? MergedAt { get; set; }
    }

    /// <summary>Series-level provider link keyed by the PARSED KEY (a resolution INPUT the reconciliation ops edit) - Provider in {Cv, External}</summary>
    public sealed class SeriesKeyLink
    {
        public string ParsedKey { get; set; } = "";
        public Provider Provider { get; set; }
        public int? ProviderKey { get; set; }
        public LinkStatus Status { get; set; }
        public int? Score { get; set; }
        public int? StoredTopScore { get; set; }
        public int AttemptCount { get; set; }
        public DateTime? AttemptedAt { get; set; }
        public string? Error { get; set; }
    }

    /// <summary>MangaUpdates link (matched AFTER resolution, so keyed by SeriesId; SeriesMergeService re-keys it)</summary>
    public sealed class MuSeriesLink
    {
        public int SeriesId { get; set; }
        public long? MuSeriesId { get; set; }
        public LinkStatus Status { get; set; }
        public string? Method { get; set; }
        public double? Confidence { get; set; }
        public string? MatchedKey { get; set; }
        public DateTime? CreatedAt { get; set; }
    }

    /// <summary>One shape for every item-level leg: Cv, Locg, Gcd, Barney, Marvel, Inducks</summary>
    public sealed class ItemProviderLink
    {
        public int ItemId { get; set; }
        public Provider Provider { get; set; }
        public string? ProviderKey { get; set; }
        public string? SecondaryKey { get; set; }
        public LinkStatus Status { get; set; }
        public string? Method { get; set; }
        public string? MatchedKey { get; set; }
        public double? Confidence { get; set; }
        public LinkQuality Quality { get; set; }
        public int? StoredTopScore { get; set; }
        public bool Applied { get; set; }
        public int AttemptCount { get; set; }
        public DateTime? AttemptedAt { get; set; }
        public string? Error { get; set; }
    }

    /// <summary>Who made it - one shape for ComicInfo creators, LOCG creators, Calibre authors (Source in {ComicInfo, Locg, Calibre, AI}); facets GROUP BY (Role, NormalizedName)</summary>
    public sealed class ItemCredit
    {
        public int ItemId { get; set; }
        public TagSource Source { get; set; }
        public int Ordinal { get; set; }
        public string? Role { get; set; }
        public string? Name { get; set; }
        public string? NormalizedName { get; set; }
        public string? ProviderPersonId { get; set; }
    }

    /// <summary>Item-level tags with provenance (ComicInfo genre/tags, Calibre subjects, CVDB-resolved names, GCD story genres, insight tags folded)</summary>
    public sealed class ItemTag
    {
        public int ItemId { get; set; }
        public string Category { get; set; } = "";
        public string Value { get; set; } = "";
        public TagSource Source { get; set; }
    }

    /// <summary>Series-level tags (AI insight tags, External subjects, MU genres, CV concepts)</summary>
    public sealed class SeriesTag
    {
        public int SeriesId { get; set; }
        public string Category { get; set; } = "";
        public string Value { get; set; } = "";
        public TagSource Source { get; set; }
    }

    /// <summary>Alias -> canonical tag</summary>
    public sealed class TagAlias
    {
        public string Category { get; set; } = "";
        public string AliasTag { get; set; } = "";
        public string? CanonicalTag { get; set; }
        public string? Source { get; set; }
    }

    /// <summary>Kids allowlist (AppliesTo: comic/book/both)</summary>
    public sealed class KidSafeTag
    {
        public string Category { get; set; } = "";
        public string Tag { get; set; } = "";
        public string? AppliesTo { get; set; }
        public DateTime? UpdatedAt { get; set; }
    }

    /// <summary>Append-only model/provider-generated metadata for an Item or a Series (GATE-1/2): rank -> confidence -> recency SELECTS the current row (IsCurrent); nothing overwritten. Maturity lives here for books.</summary>
    public sealed class Insight
    {
        public int Id { get; set; }
        public SubjectKind SubjectKind { get; set; }
        public int? SubjectId { get; set; }
        public string ModelId { get; set; } = "";
        public int Rank { get; set; }
        public Confidence Confidence { get; set; }
        public bool Recognized { get; set; }
        public int? Rating { get; set; }
        public string? Synopsis { get; set; }
        public string? Author { get; set; }
        public string? Artist { get; set; }
        public int? YearBegin { get; set; }
        public int? YearEnd { get; set; }
        public int? Maturity { get; set; }
        public string? ReviewFlag { get; set; }
        public string? SourceKey { get; set; }
        public DateTime? GeneratedAt { get; set; }
        public bool IsCurrent { get; set; }
    }

    /// <summary>Tags of one insight row (folded into ItemTag/SeriesTag with Source=AI when the row is current)</summary>
    public sealed class InsightTag
    {
        public int InsightId { get; set; }
        public string Category { get; set; } = "";
        public string Value { get; set; } = "";
    }

    /// <summary>Every rating with provenance, normalized to 0-100 at write time (RawValue/RawScale kept); Item/Series.ResolvedRating is materialized from it - browse never joins this</summary>
    public sealed class Rating
    {
        public SubjectKind TargetKind { get; set; }
        public int TargetId { get; set; }
        public RatingSource Source { get; set; }
        public int? Value { get; set; }
        public double? RawValue { get; set; }
        public string? RawScale { get; set; }
        public int? Count { get; set; }
        public string? Note { get; set; }
        public bool IsOverride { get; set; }
        public string ModelId { get; set; } = "";
        public DateTime? GeneratedAt { get; set; }
    }

    /// <summary>DERIVED per-issue reading position (books-reading-order)</summary>
    public sealed class ReadingOrderEntry
    {
        public int ItemId { get; set; }
        public int? SeriesId { get; set; }
        public int? ReadTier { get; set; }
        public double? ReadNumber { get; set; }
        public double? ReadNumberSuffix { get; set; }
        public string? ReadDate { get; set; }
        public DatePrecision ReadDatePrecision { get; set; }
        public int? ReadIndex { get; set; }
        public int ReadCount { get; set; }
        public ReadingOrderSource Source { get; set; }
        public Confidence Confidence { get; set; }
        public string? Notes { get; set; }
        public DateTime? ComputedAt { get; set; }
    }

    /// <summary>DERIVED containment (books-containment); ParentItemId -> Item</summary>
    public sealed class CollectionNode
    {
        public int ItemId { get; set; }
        public int? SeriesId { get; set; }
        public CollectionLevel Level { get; set; }
        public TrackRole TrackRole { get; set; }
        public int? SpanStart { get; set; }
        public int? SpanEnd { get; set; }
        public int ContainsCount { get; set; }
        public int? ParentItemId { get; set; }
        public SpanSource SpanSource { get; set; }
        public string? SpanLabel { get; set; }
    }

    /// <summary>Collected-edition spans from the four sources (Locg, Gcd, Cv, Curated) - containment precedence Locg > Gcd > Cv > Curated</summary>
    public sealed class CollectedEditionSpan
    {
        public int ItemId { get; set; }
        public EditionSource Source { get; set; }
        public int? SeriesId { get; set; }
        public double? IssueStart { get; set; }
        public double? IssueEnd { get; set; }
        public string? EditionTitle { get; set; }
        public string? ProviderRef { get; set; }
        public bool Contiguous { get; set; }
        public double? Confidence { get; set; }
        public string? Note { get; set; }
        public DateTime? CreatedAt { get; set; }
    }

    /// <summary>ComicVine volume (series-level facts the modal shows)</summary>
    public sealed class CvVolume
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public int? StartYear { get; set; }
        public string? PublisherName { get; set; }
        public int? CountOfIssues { get; set; }
        public string? Deck { get; set; }
        public string? Description { get; set; }
        public string? ImageUrl { get; set; }
        public string? SiteDetailUrl { get; set; }
        public DateTime? FetchedAt { get; set; }
    }

    /// <summary>ComicVine issue (cover dates feed reading order; description is a synopsis source)</summary>
    public sealed class CvIssue
    {
        public int Id { get; set; }
        public int? VolumeId { get; set; }
        public string? Name { get; set; }
        public string? IssueNumber { get; set; }
        public string? CoverDate { get; set; }
        public string? StoreDate { get; set; }
        public string? Deck { get; set; }
        public string? Description { get; set; }
        public string? ImageUrl { get; set; }
        public string? SiteDetailUrl { get; set; }
        public DateTime? FetchedAt { get; set; }
    }

    /// <summary>LOCG record, HOT SUBSET: only rows an ItemProviderLink(Locg) references and only the columns the modal/projection read (GATE question 15)</summary>
    public sealed class LocgComic
    {
        public int LocgComicId { get; set; }
        public int? LocgSeriesId { get; set; }
        public string? SeriesName { get; set; }
        public string? Title { get; set; }
        public string? IssueNumber { get; set; }
        public string? Format { get; set; }
        public string? CoverDate { get; set; }
        public int? PageCount { get; set; }
        public string? Description { get; set; }
        public double? CommunityRating { get; set; }
        public int? RatingCount { get; set; }
        public bool IsKey { get; set; }
        public string? KeyType { get; set; }
        public string? Isbn { get; set; }
        public string? Upc { get; set; }
        public string? CoverPrice { get; set; }
        public string? CoverUrl { get; set; }
        public int? StoryCount { get; set; }
        public DateTime? ScrapedAt { get; set; }
    }

    /// <summary>MangaUpdates series (runtime leg: description + genres)</summary>
    public sealed class MuSeries
    {
        public long Id { get; set; }
        public string? Title { get; set; }
        public int? Year { get; set; }
        public string? Type { get; set; }
        public string? Status { get; set; }
        public bool Completed { get; set; }
        public string? Description { get; set; }
        public double? BayesianRating { get; set; }
        public string? Url { get; set; }
        public DateTime? ScrapedAt { get; set; }
    }

    /// <summary>Open Library / Google Books work (the ComicVine-miss fallback leg)</summary>
    public sealed class ExternalWork
    {
        public int Id { get; set; }
        public string? Provider { get; set; }
        public string? ProviderKey { get; set; }
        public string? Title { get; set; }
        public string? Authors { get; set; }
        public string? Publisher { get; set; }
        public int? FirstPublishYear { get; set; }
        public string? Description { get; set; }
        public string? CoverImageUrl { get; set; }
        public string? Isbn { get; set; }
        public string? InfoUrl { get; set; }
        public DateTime? FetchedAt { get; set; }
    }

    /// <summary>2000AD prog dates (reading-order recompute input; 2,313 rows)</summary>
    public sealed class BarneyProg
    {
        public int ProgNo { get; set; }
        public string? CoverDate { get; set; }
        public string? Price { get; set; }
        public string? StripsJson { get; set; }
        public DateTime? ScrapedAt { get; set; }
    }

    /// <summary>CVDB#### -> ComicVine entity name</summary>
    public sealed class CvdbResolution
    {
        public string CvdbTag { get; set; } = "";
        public int? ComicvineId { get; set; }
        public string? ResolvedName { get; set; }
        public string? EntityType { get; set; }
        public string? Status { get; set; }
        public DateTime? ResolvedAt { get; set; }
    }

    /// <summary>Reconciliation audit log + review queue (reversible)</summary>
    public sealed class SeriesInferenceDecision
    {
        public int Id { get; set; }
        public string? SeriesKey { get; set; }
        public string? Class { get; set; }
        public string? Action { get; set; }
        public string? Target { get; set; }
        public string? Confidence { get; set; }
        public string? EvidenceJson { get; set; }
        public string? State { get; set; }
        public string? UndoJson { get; set; }
        public string? DecidedBy { get; set; }
        public DateTime? DecidedAt { get; set; }
    }

    /// <summary>Mismatch detection triage state</summary>
    public sealed class SeriesMatchReview
    {
        public int Id { get; set; }
        public string? Scope { get; set; }
        public string? Key { get; set; }
        public string? State { get; set; }
        public string? Note { get; set; }
        public string? DecidedBy { get; set; }
        public DateTime? DecidedAt { get; set; }
    }

    /// <summary>Dedup groups</summary>
    public sealed class DuplicateGroup
    {
        public int Id { get; set; }
        public int? Relationship { get; set; }
        public string? Confidence { get; set; }
        public string? Evidence { get; set; }
        public int? SuggestedKeeperItemId { get; set; }
        public string? ReviewState { get; set; }
        public DateTime? DetectedAt { get; set; }
    }

    /// <summary>Dedup group members</summary>
    public sealed class DuplicateMember
    {
        public int Id { get; set; }
        public int DuplicateGroupId { get; set; }
        public int ItemId { get; set; }
        public string? Role { get; set; }
        public bool SoleFileInFolder { get; set; }
    }

    /// <summary>One row per MT user x item: reading position + want/favorite/hidden (lastPage -1 = Finished is the ONLY finish signal; any write clears HiddenFromHistory)</summary>
    public sealed class UserItemState
    {
        public int UserId { get; set; }
        public int ItemId { get; set; }
        public int LastPage { get; set; }
        public int? LastSpineItemIndex { get; set; }
        public double? LastScrollPercent { get; set; }
        public ReadStatus Status { get; set; }
        public bool WantToRead { get; set; }
        public bool Favorite { get; set; }
        public bool HiddenFromHistory { get; set; }
        public DateTime? UpdatedAt { get; set; }
    }

    /// <summary>Per-user marks on a group (series key = SeriesId; volume/collection/publisher/decade keys as the batch endpoint addresses them)</summary>
    public sealed class GroupMark
    {
        public int UserId { get; set; }
        public GroupType GroupType { get; set; }
        public string GroupKey { get; set; } = "";
        public bool IsRead { get; set; }
        public bool WantToRead { get; set; }
        public bool IsFavorite { get; set; }
        public int? Rating { get; set; }
        public string? Notes { get; set; }
        public DateTime? UpdatedAt { get; set; }
    }

    /// <summary>Registry of DERIVED tables/columns: the job that rebuilds each, its input fingerprint, last rebuild - replaces the SystemState fingerprint rows and enforces the edit-inputs rule structurally</summary>
    public sealed class DerivedTable
    {
        public string Name { get; set; } = "";
        public string RebuildJob { get; set; } = "";
        public string? InputFingerprint { get; set; }
        public DateTime? LastRebuiltAt { get; set; }
        public int RowCount { get; set; }
    }

    /// <summary>Generic KV (scan bookkeeping only; fingerprints moved to DerivedTable)</summary>
    public sealed class SystemState
    {
        public string Key { get; set; } = "";
        public string? Value { get; set; }
    }

    /// <summary>Audit of scans/imports (replaces boot-time backfills)</summary>
    public sealed class ScanRun
    {
        public int Id { get; set; }
        public int? RootId { get; set; }
        public string? Kind { get; set; }
        public DateTime? StartedAt { get; set; }
        public DateTime? FinishedAt { get; set; }
        public int ItemsSeen { get; set; }
        public int Added { get; set; }
        public int Changed { get; set; }
        public int Removed { get; set; }
        public string? Error { get; set; }
    }

    /// <summary>books-migrate-v1 resume state</summary>
    public sealed class MigrationProgress
    {
        public string Stage { get; set; } = "";
        public string? Cursor { get; set; }
        public int Processed { get; set; }
        public int Total { get; set; }
        public DateTime? FinishedAt { get; set; }
    }

    /// <summary>Last-seen identity payload per MT user (cache warmer input)</summary>
    public sealed class KnownIdentity
    {
        public int UserId { get; set; }
        public string? Username { get; set; }
        public bool IsAdmin { get; set; }
        public int MaturityCeiling { get; set; }
        public string? KidsStyle { get; set; }
        public DateTime? LastSeenAt { get; set; }
    }

}
