// <auto-generated> by scripts/books/gen/gen_entities.py from docs/books/v2-mapping.json — do not edit by hand.
using Microsoft.EntityFrameworkCore;

namespace MovieTheater.Books.Db
{
    /// <summary>The hot catalog (books.db). ItemFts (FTS5) is created by the migration's raw SQL and queried through FtsQueries, not mapped.</summary>
    public sealed class BooksDb : DbContext
    {
        public BooksDb(DbContextOptions<BooksDb> options) : base(options) { }

        public DbSet<LibraryRoot> LibraryRoots => Set<LibraryRoot>();
        public DbSet<Folder> Folders => Set<Folder>();
        public DbSet<Publisher> Publishers => Set<Publisher>();
        public DbSet<Item> Items => Set<Item>();
        public DbSet<ItemState> ItemStates => Set<ItemState>();
        public DbSet<ItemSignature> ItemSignatures => Set<ItemSignature>();
        public DbSet<ComicEmbedded> ComicEmbeddeds => Set<ComicEmbedded>();
        public DbSet<BookDetail> BookDetails => Set<BookDetail>();
        public DbSet<ComicDetail> ComicDetails => Set<ComicDetail>();
        public DbSet<Series> Series => Set<Series>();
        public DbSet<SeriesAlias> SeriesAliases => Set<SeriesAlias>();
        public DbSet<SeriesMerge> SeriesMerges => Set<SeriesMerge>();
        public DbSet<SeriesKeyLink> SeriesKeyLinks => Set<SeriesKeyLink>();
        public DbSet<MuSeriesLink> MuSeriesLinks => Set<MuSeriesLink>();
        public DbSet<ItemProviderLink> ItemProviderLinks => Set<ItemProviderLink>();
        public DbSet<ItemCredit> ItemCredits => Set<ItemCredit>();
        public DbSet<ItemTag> ItemTags => Set<ItemTag>();
        public DbSet<SeriesTag> SeriesTags => Set<SeriesTag>();
        public DbSet<TagAlias> TagAlias => Set<TagAlias>();
        public DbSet<KidSafeTag> KidSafeTags => Set<KidSafeTag>();
        public DbSet<Insight> Insights => Set<Insight>();
        public DbSet<InsightTag> InsightTags => Set<InsightTag>();
        public DbSet<Rating> Ratings => Set<Rating>();
        public DbSet<ReadingOrderEntry> ReadingOrderEntries => Set<ReadingOrderEntry>();
        public DbSet<CollectionNode> CollectionNodes => Set<CollectionNode>();
        public DbSet<CollectedEditionSpan> CollectedEditionSpans => Set<CollectedEditionSpan>();
        public DbSet<CvVolume> CvVolumes => Set<CvVolume>();
        public DbSet<CvIssue> CvIssues => Set<CvIssue>();
        public DbSet<LocgComic> LocgComics => Set<LocgComic>();
        public DbSet<MuSeries> MuSeries => Set<MuSeries>();
        public DbSet<ExternalWork> ExternalWorks => Set<ExternalWork>();
        public DbSet<BarneyProg> BarneyProgs => Set<BarneyProg>();
        public DbSet<CvdbResolution> CvdbResolutions => Set<CvdbResolution>();
        public DbSet<SeriesInferenceDecision> SeriesInferenceDecisions => Set<SeriesInferenceDecision>();
        public DbSet<SeriesMatchReview> SeriesMatchReviews => Set<SeriesMatchReview>();
        public DbSet<DuplicateGroup> DuplicateGroups => Set<DuplicateGroup>();
        public DbSet<DuplicateMember> DuplicateMembers => Set<DuplicateMember>();
        public DbSet<UserItemState> UserItemStates => Set<UserItemState>();
        public DbSet<GroupMark> GroupMarks => Set<GroupMark>();
        public DbSet<DerivedTable> DerivedTables => Set<DerivedTable>();
        public DbSet<SystemState> SystemStates => Set<SystemState>();
        public DbSet<ScanRun> ScanRuns => Set<ScanRun>();
        public DbSet<MigrationProgress> MigrationProgress => Set<MigrationProgress>();
        public DbSet<KnownIdentity> KnownIdentities => Set<KnownIdentity>();

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<LibraryRoot>(e =>
            {
                e.ToTable("LibraryRoot");
                e.HasKey(x => x.Id);
                e.Property(x => x.Id).ValueGeneratedNever();
                e.HasIndex(x => x.Path).IsUnique();
                e.Property(x => x.Kind).HasDefaultValue(ItemKind.Comic);
                e.Property(x => x.IsCalibre).HasDefaultValue(false);
                e.Property(x => x.Enabled).HasDefaultValue(false);
            });
            modelBuilder.Entity<Folder>(e =>
            {
                e.ToTable("Folder");
                e.HasKey(x => x.Id);
                e.Property(x => x.Id).ValueGeneratedNever();
                e.Property(x => x.RootId).HasDefaultValue(0);
                e.HasOne<LibraryRoot>().WithMany().HasForeignKey(x => x.RootId).OnDelete(DeleteBehavior.Restrict);
                e.HasOne<Folder>().WithMany().HasForeignKey(x => x.ParentId).OnDelete(DeleteBehavior.Restrict);
                e.Property(x => x.Kind).HasDefaultValue(ItemKind.Comic);
                e.HasIndex(x => x.Path).IsUnique();
                e.Property(x => x.Depth).HasDefaultValue(0);
                e.Property(x => x.DirectChildCount).HasDefaultValue(0);
                e.Property(x => x.DescendantItemCount).HasDefaultValue(0);
                e.Property(x => x.HasIcon).HasDefaultValue(false);
                e.HasIndex(x => x.ParentId);
                e.HasIndex(x => x.TopFolderId);
                e.HasIndex(x => x.NormalizedName);
            });
            modelBuilder.Entity<Publisher>(e =>
            {
                e.ToTable("Publisher");
                e.HasKey(x => x.Id);
                e.Property(x => x.Id).ValueGeneratedNever();
                e.HasIndex(x => x.Name).IsUnique();
            });
            modelBuilder.Entity<Item>(e =>
            {
                e.ToTable("Item");
                e.HasKey(x => x.Id);
                e.Property(x => x.Id).ValueGeneratedNever();
                e.Property(x => x.RootId).HasDefaultValue(0);
                e.HasOne<LibraryRoot>().WithMany().HasForeignKey(x => x.RootId).OnDelete(DeleteBehavior.Restrict);
                e.Property(x => x.FolderId).HasDefaultValue(0);
                e.HasOne(x => x.Folder).WithMany().HasForeignKey(x => x.FolderId).OnDelete(DeleteBehavior.Restrict);
                e.Property(x => x.Kind).HasDefaultValue(ItemKind.Comic);
                e.HasIndex(x => x.Path).IsUnique();
                e.Property(x => x.ContainerFormat).HasDefaultValue(ContainerFormat.Cbz);
                e.Property(x => x.FileSize).HasDefaultValue(0);
                e.HasIndex(x => x.CalibreBookId).IsUnique();
                e.HasOne(x => x.Publisher).WithMany().HasForeignKey(x => x.PublisherId).OnDelete(DeleteBehavior.Restrict);
                e.HasOne(x => x.Series).WithMany().HasForeignKey(x => x.SeriesId).OnDelete(DeleteBehavior.Restrict);
                e.Property(x => x.IsExcluded).HasDefaultValue(false);
                e.Property(x => x.KeepInDirectory).HasDefaultValue(false);
                e.Property(x => x.ResolvedDatePrecision).HasDefaultValue(DatePrecision.None);
                e.Property(x => x.ResolvedSynopsisSource).HasDefaultValue(SynopsisSource.None);
                e.HasIndex(x => new { x.Kind, x.ResolvedSeries, x.Id });
                e.HasIndex(x => new { x.Kind, x.ResolvedYear, x.IndexedAt, x.Id }).IsDescending(false, true, true, false);
                e.HasIndex(x => new { x.Kind, x.ResolvedRating, x.Id }).IsDescending(false, true, false);
                e.HasIndex(x => new { x.Kind, x.IndexedAt, x.Id }).IsDescending(false, true, false);
                e.HasIndex(x => new { x.SeriesId, x.Id });
                e.HasIndex(x => x.FolderId);
                e.HasIndex(x => x.TopFolderId);
                e.HasIndex(x => x.PublisherId);
                e.HasIndex(x => new { x.Kind, x.NormalizedTitle, x.Id });
                e.HasIndex(x => new { x.Kind, x.ResolvedPublisher, x.Id });
            });
            modelBuilder.Entity<ItemState>(e =>
            {
                e.ToTable("ItemState");
                e.HasKey(x => x.ItemId);
                e.Property(x => x.ItemId).ValueGeneratedNever();
                e.HasOne<Item>().WithOne(x => x.State).HasForeignKey<ItemState>(x => x.ItemId).OnDelete(DeleteBehavior.Cascade);
                e.Property(x => x.IsBroken).HasDefaultValue(false);
            });
            modelBuilder.Entity<ItemSignature>(e =>
            {
                e.ToTable("ItemSignature");
                e.HasKey(x => x.ItemId);
                e.Property(x => x.ItemId).ValueGeneratedNever();
                e.HasOne<Item>().WithOne(x => x.Signature).HasForeignKey<ItemSignature>(x => x.ItemId).OnDelete(DeleteBehavior.Cascade);
                e.HasIndex(x => x.ContentFingerprint);
                e.HasIndex(x => x.CoverPHash);
            });
            modelBuilder.Entity<ComicEmbedded>(e =>
            {
                e.ToTable("ComicEmbedded");
                e.HasKey(x => x.ItemId);
                e.Property(x => x.ItemId).ValueGeneratedNever();
                e.HasOne<Item>().WithOne(x => x.Embedded).HasForeignKey<ComicEmbedded>(x => x.ItemId).OnDelete(DeleteBehavior.Cascade);
            });
            modelBuilder.Entity<BookDetail>(e =>
            {
                e.ToTable("BookDetail");
                e.HasKey(x => x.ItemId);
                e.Property(x => x.ItemId).ValueGeneratedNever();
                e.HasOne<Item>().WithOne(x => x.Book).HasForeignKey<BookDetail>(x => x.ItemId).OnDelete(DeleteBehavior.Cascade);
                e.HasIndex(x => x.Isbn);
                e.HasIndex(x => new { x.SeriesName, x.SeriesIndex });
            });
            modelBuilder.Entity<ComicDetail>(e =>
            {
                e.ToTable("ComicDetail");
                e.HasKey(x => x.ItemId);
                e.Property(x => x.ItemId).ValueGeneratedNever();
                e.HasOne<Item>().WithOne(x => x.Comic).HasForeignKey<ComicDetail>(x => x.ItemId).OnDelete(DeleteBehavior.Cascade);
                e.Property(x => x.Format).HasDefaultValue(ComicFormat.SingleIssue);
                e.Property(x => x.IsCollection).HasDefaultValue(false);
                e.Property(x => x.Confidence).HasDefaultValue(Confidence.Unknown);
                e.Property(x => x.SeriesSource).HasDefaultValue(ParseSource.None);
                e.Property(x => x.IssueSource).HasDefaultValue(ParseSource.None);
                e.Property(x => x.YearSource).HasDefaultValue(ParseSource.None);
                e.Property(x => x.PublisherSource).HasDefaultValue(ParseSource.None);
                e.HasIndex(x => x.ParsedSeriesKey);
                e.HasIndex(x => x.EventName);
                e.HasIndex(x => x.Year);
            });
            modelBuilder.Entity<Series>(e =>
            {
                e.ToTable("Series");
                e.HasKey(x => x.Id);
                e.Property(x => x.Id).ValueGeneratedNever();
                e.HasIndex(x => x.CanonicalKey).IsUnique();
                e.Property(x => x.IssueCount).HasDefaultValue(0);
                e.Property(x => x.IsOngoing).HasDefaultValue(false);
                e.Property(x => x.ResolvedSynopsisSource).HasDefaultValue(SynopsisSource.None);
                e.HasIndex(x => new { x.Name, x.Id });
                e.HasIndex(x => x.ParsedKey);
                e.HasIndex(x => x.Franchise);
                e.HasIndex(x => new { x.ResolvedRating, x.Id }).IsDescending(true, false);
            });
            modelBuilder.Entity<SeriesAlias>(e =>
            {
                e.ToTable("SeriesAlias");
                e.HasKey(x => x.ParsedKey);
                e.Property(x => x.SeriesId).HasDefaultValue(0);
                e.HasOne<Series>().WithMany().HasForeignKey(x => x.SeriesId).OnDelete(DeleteBehavior.Restrict);
                e.HasIndex(x => x.SeriesId);
            });
            modelBuilder.Entity<SeriesMerge>(e =>
            {
                e.ToTable("SeriesMerge");
                e.HasKey(x => x.OldSeriesId);
                e.Property(x => x.OldSeriesId).ValueGeneratedNever();
            });
            modelBuilder.Entity<SeriesKeyLink>(e =>
            {
                e.ToTable("SeriesKeyLink");
                e.HasKey(x => new { x.ParsedKey, x.Provider });
                e.Property(x => x.Status).HasDefaultValue(LinkStatus.Pending);
                e.Property(x => x.AttemptCount).HasDefaultValue(0);
                e.HasIndex(x => new { x.Provider, x.ProviderKey });
                e.HasIndex(x => x.Status);
            });
            modelBuilder.Entity<MuSeriesLink>(e =>
            {
                e.ToTable("MuSeriesLink");
                e.HasKey(x => x.SeriesId);
                e.Property(x => x.SeriesId).ValueGeneratedNever();
                e.HasOne<Series>().WithMany().HasForeignKey(x => x.SeriesId).OnDelete(DeleteBehavior.Restrict);
                e.Property(x => x.Status).HasDefaultValue(LinkStatus.Pending);
            });
            modelBuilder.Entity<ItemProviderLink>(e =>
            {
                e.ToTable("ItemProviderLink");
                e.HasKey(x => new { x.ItemId, x.Provider });
                e.HasOne<Item>().WithMany().HasForeignKey(x => x.ItemId).OnDelete(DeleteBehavior.Restrict);
                e.Property(x => x.Status).HasDefaultValue(LinkStatus.Pending);
                e.Property(x => x.Quality).HasDefaultValue(LinkQuality.Unknown);
                e.Property(x => x.Applied).HasDefaultValue(false);
                e.Property(x => x.AttemptCount).HasDefaultValue(0);
                e.HasIndex(x => new { x.Provider, x.ProviderKey });
                e.HasIndex(x => new { x.Provider, x.Status });
            });
            modelBuilder.Entity<ItemCredit>(e =>
            {
                e.ToTable("ItemCredit");
                e.HasKey(x => new { x.ItemId, x.Source, x.Ordinal });
                e.HasOne<Item>().WithMany().HasForeignKey(x => x.ItemId).OnDelete(DeleteBehavior.Restrict);
                e.HasIndex(x => new { x.Role, x.NormalizedName, x.ItemId });
            });
            modelBuilder.Entity<ItemTag>(e =>
            {
                e.ToTable("ItemTag");
                e.HasKey(x => new { x.ItemId, x.Category, x.Value, x.Source });
                e.HasOne<Item>().WithMany().HasForeignKey(x => x.ItemId).OnDelete(DeleteBehavior.Restrict);
                e.HasIndex(x => new { x.Category, x.Value, x.ItemId });
            });
            modelBuilder.Entity<SeriesTag>(e =>
            {
                e.ToTable("SeriesTag");
                e.HasKey(x => new { x.SeriesId, x.Category, x.Value, x.Source });
                e.HasOne<Series>().WithMany().HasForeignKey(x => x.SeriesId).OnDelete(DeleteBehavior.Restrict);
                e.HasIndex(x => new { x.Category, x.Value, x.SeriesId });
            });
            modelBuilder.Entity<TagAlias>(e =>
            {
                e.ToTable("TagAlias");
                e.HasKey(x => new { x.Category, x.AliasTag });
            });
            modelBuilder.Entity<KidSafeTag>(e =>
            {
                e.ToTable("KidSafeTag");
                e.HasKey(x => new { x.Category, x.Tag });
            });
            modelBuilder.Entity<Insight>(e =>
            {
                e.ToTable("Insight");
                e.HasKey(x => x.Id);
                e.Property(x => x.Id).ValueGeneratedNever();
                e.Property(x => x.SubjectKind).HasDefaultValue(SubjectKind.Item);
                e.Property(x => x.Rank).HasDefaultValue(0);
                e.Property(x => x.Confidence).HasDefaultValue(Confidence.Unknown);
                e.Property(x => x.Recognized).HasDefaultValue(false);
                e.Property(x => x.IsCurrent).HasDefaultValue(false);
                e.HasIndex(x => new { x.SubjectKind, x.SubjectId, x.IsCurrent });
                e.HasIndex(x => new { x.SubjectKind, x.Maturity }).HasFilter("\"IsCurrent\" = 1");
            });
            modelBuilder.Entity<InsightTag>(e =>
            {
                e.ToTable("InsightTag");
                e.HasKey(x => new { x.InsightId, x.Category, x.Value });
                e.HasOne<Insight>().WithMany().HasForeignKey(x => x.InsightId).OnDelete(DeleteBehavior.Restrict);
            });
            modelBuilder.Entity<Rating>(e =>
            {
                e.ToTable("Rating");
                e.HasKey(x => new { x.TargetKind, x.TargetId, x.Source });
                e.Property(x => x.IsOverride).HasDefaultValue(false);
            });
            modelBuilder.Entity<ReadingOrderEntry>(e =>
            {
                e.ToTable("ReadingOrderEntry");
                e.HasKey(x => x.ItemId);
                e.Property(x => x.ItemId).ValueGeneratedNever();
                e.HasOne<Item>().WithMany().HasForeignKey(x => x.ItemId).OnDelete(DeleteBehavior.Restrict);
                e.Property(x => x.ReadDatePrecision).HasDefaultValue(DatePrecision.None);
                e.Property(x => x.ReadCount).HasDefaultValue(0);
                e.Property(x => x.Source).HasDefaultValue(ReadingOrderSource.Unordered);
                e.Property(x => x.Confidence).HasDefaultValue(Confidence.Unknown);
                e.HasIndex(x => new { x.SeriesId, x.ReadIndex });
            });
            modelBuilder.Entity<CollectionNode>(e =>
            {
                e.ToTable("CollectionNode");
                e.HasKey(x => x.ItemId);
                e.Property(x => x.ItemId).ValueGeneratedNever();
                e.HasOne<Item>().WithMany().HasForeignKey(x => x.ItemId).OnDelete(DeleteBehavior.Restrict);
                e.Property(x => x.Level).HasDefaultValue(CollectionLevel.Issue);
                e.Property(x => x.TrackRole).HasDefaultValue(TrackRole.Primary);
                e.Property(x => x.ContainsCount).HasDefaultValue(0);
                e.HasOne<Item>().WithMany().HasForeignKey(x => x.ParentItemId).OnDelete(DeleteBehavior.Restrict);
                e.Property(x => x.SpanSource).HasDefaultValue(SpanSource.None);
                e.HasIndex(x => x.SeriesId);
                e.HasIndex(x => x.ParentItemId);
                e.HasIndex(x => x.ContainsCount).IsDescending(true);
            });
            modelBuilder.Entity<CollectedEditionSpan>(e =>
            {
                e.ToTable("CollectedEditionSpan");
                e.HasKey(x => new { x.ItemId, x.Source });
                e.HasOne<Item>().WithMany().HasForeignKey(x => x.ItemId).OnDelete(DeleteBehavior.Restrict);
                e.Property(x => x.Contiguous).HasDefaultValue(false);
                e.HasIndex(x => x.SeriesId);
            });
            modelBuilder.Entity<CvVolume>(e =>
            {
                e.ToTable("CvVolume");
                e.HasKey(x => x.Id);
                e.Property(x => x.Id).ValueGeneratedNever();
            });
            modelBuilder.Entity<CvIssue>(e =>
            {
                e.ToTable("CvIssue");
                e.HasKey(x => x.Id);
                e.Property(x => x.Id).ValueGeneratedNever();
                e.HasIndex(x => x.VolumeId);
            });
            modelBuilder.Entity<LocgComic>(e =>
            {
                e.ToTable("LocgComic");
                e.HasKey(x => x.LocgComicId);
                e.Property(x => x.LocgComicId).ValueGeneratedNever();
                e.Property(x => x.IsKey).HasDefaultValue(false);
            });
            modelBuilder.Entity<MuSeries>(e =>
            {
                e.ToTable("MuSeries");
                e.HasKey(x => x.Id);
                e.Property(x => x.Id).ValueGeneratedNever();
                e.Property(x => x.Completed).HasDefaultValue(false);
            });
            modelBuilder.Entity<ExternalWork>(e =>
            {
                e.ToTable("ExternalWork");
                e.HasKey(x => x.Id);
                e.Property(x => x.Id).ValueGeneratedNever();
                e.HasIndex(x => new { x.Provider, x.ProviderKey }).IsUnique();
            });
            modelBuilder.Entity<BarneyProg>(e =>
            {
                e.ToTable("BarneyProg");
                e.HasKey(x => x.ProgNo);
                e.Property(x => x.ProgNo).ValueGeneratedNever();
            });
            modelBuilder.Entity<CvdbResolution>(e =>
            {
                e.ToTable("CvdbResolution");
                e.HasKey(x => x.CvdbTag);
            });
            modelBuilder.Entity<SeriesInferenceDecision>(e =>
            {
                e.ToTable("SeriesInferenceDecision");
                e.HasKey(x => x.Id);
                e.Property(x => x.Id).ValueGeneratedNever();
                e.HasIndex(x => new { x.State, x.Class });
            });
            modelBuilder.Entity<SeriesMatchReview>(e =>
            {
                e.ToTable("SeriesMatchReview");
                e.HasKey(x => x.Id);
                e.Property(x => x.Id).ValueGeneratedNever();
                e.HasIndex(x => new { x.Scope, x.Key }).IsUnique();
            });
            modelBuilder.Entity<DuplicateGroup>(e =>
            {
                e.ToTable("DuplicateGroup");
                e.HasKey(x => x.Id);
                e.Property(x => x.Id).ValueGeneratedNever();
            });
            modelBuilder.Entity<DuplicateMember>(e =>
            {
                e.ToTable("DuplicateMember");
                e.HasKey(x => x.Id);
                e.Property(x => x.Id).ValueGeneratedNever();
                e.Property(x => x.DuplicateGroupId).HasDefaultValue(0);
                e.HasOne<DuplicateGroup>().WithMany().HasForeignKey(x => x.DuplicateGroupId).OnDelete(DeleteBehavior.Restrict);
                e.Property(x => x.ItemId).HasDefaultValue(0);
                e.HasOne<Item>().WithMany().HasForeignKey(x => x.ItemId).OnDelete(DeleteBehavior.Restrict);
                e.Property(x => x.SoleFileInFolder).HasDefaultValue(false);
                e.HasIndex(x => x.ItemId);
                e.HasIndex(x => x.DuplicateGroupId);
            });
            modelBuilder.Entity<UserItemState>(e =>
            {
                e.ToTable("UserItemState");
                e.HasKey(x => new { x.UserId, x.ItemId });
                e.HasOne<Item>().WithMany().HasForeignKey(x => x.ItemId).OnDelete(DeleteBehavior.Restrict);
                e.Property(x => x.LastPage).HasDefaultValue(0);
                e.Property(x => x.Status).HasDefaultValue(ReadStatus.Unread);
                e.Property(x => x.WantToRead).HasDefaultValue(false);
                e.Property(x => x.Favorite).HasDefaultValue(false);
                e.Property(x => x.HiddenFromHistory).HasDefaultValue(false);
                e.HasIndex(x => new { x.UserId, x.UpdatedAt }).IsDescending(false, true);
                e.HasIndex(x => new { x.UserId, x.WantToRead });
                e.HasIndex(x => x.ItemId);
            });
            modelBuilder.Entity<GroupMark>(e =>
            {
                e.ToTable("GroupMark");
                e.HasKey(x => new { x.UserId, x.GroupType, x.GroupKey });
                e.Property(x => x.IsRead).HasDefaultValue(false);
                e.Property(x => x.WantToRead).HasDefaultValue(false);
                e.Property(x => x.IsFavorite).HasDefaultValue(false);
                e.HasIndex(x => new { x.UserId, x.GroupType, x.WantToRead });
            });
            modelBuilder.Entity<DerivedTable>(e =>
            {
                e.ToTable("DerivedTable");
                e.HasKey(x => x.Name);
                e.Property(x => x.RowCount).HasDefaultValue(0);
            });
            modelBuilder.Entity<SystemState>(e =>
            {
                e.ToTable("SystemState");
                e.HasKey(x => x.Key);
            });
            modelBuilder.Entity<ScanRun>(e =>
            {
                e.ToTable("ScanRun");
                e.HasKey(x => x.Id);
                e.Property(x => x.Id).ValueGeneratedNever();
                e.Property(x => x.ItemsSeen).HasDefaultValue(0);
                e.Property(x => x.Added).HasDefaultValue(0);
                e.Property(x => x.Changed).HasDefaultValue(0);
                e.Property(x => x.Removed).HasDefaultValue(0);
            });
            modelBuilder.Entity<MigrationProgress>(e =>
            {
                e.ToTable("MigrationProgress");
                e.HasKey(x => x.Stage);
                e.Property(x => x.Processed).HasDefaultValue(0);
                e.Property(x => x.Total).HasDefaultValue(0);
            });
            modelBuilder.Entity<KnownIdentity>(e =>
            {
                e.ToTable("KnownIdentity");
                e.HasKey(x => x.UserId);
                e.Property(x => x.UserId).ValueGeneratedNever();
                e.Property(x => x.IsAdmin).HasDefaultValue(false);
                e.Property(x => x.MaturityCeiling).HasDefaultValue(0);
            });
        }
    }
}
