// <auto-generated> by scripts/books/gen/gen_entities.py from docs/books/v2-mapping.json — do not edit by hand.
using Microsoft.EntityFrameworkCore;

namespace MovieTheater.Books.Db
{
    /// <summary>The offline warehouse (books-legs.db): provider raw rows, containment edges, caches, candidate JSON.</summary>
    public sealed class BooksLegsDb : DbContext
    {
        public BooksLegsDb(DbContextOptions<BooksLegsDb> options) : base(options) { }

        public DbSet<LocgComicRaw> LocgComicRaws => Set<LocgComicRaw>();
        public DbSet<LocgCreatorRaw> LocgCreatorRaws => Set<LocgCreatorRaw>();
        public DbSet<LocgContainment> LocgContainments => Set<LocgContainment>();
        public DbSet<LocgSeries> LocgSeries => Set<LocgSeries>();
        public DbSet<LocgSeriesInference> LocgSeriesInferences => Set<LocgSeriesInference>();
        public DbSet<GcdIssue> GcdIssues => Set<GcdIssue>();
        public DbSet<GcdSeries> GcdSeries => Set<GcdSeries>();
        public DbSet<OpenLibraryEdition> OpenLibraryEditions => Set<OpenLibraryEdition>();
        public DbSet<OpenLibraryWork> OpenLibraryWorks => Set<OpenLibraryWork>();
        public DbSet<OlSeriesInference> OlSeriesInferences => Set<OlSeriesInference>();
        public DbSet<MarvelSeries> MarvelSeries => Set<MarvelSeries>();
        public DbSet<MarvelIssue> MarvelIssues => Set<MarvelIssue>();
        public DbSet<MarvelSeriesLink> MarvelSeriesLinks => Set<MarvelSeriesLink>();
        public DbSet<BarcodeScan> BarcodeScans => Set<BarcodeScan>();
        public DbSet<ProviderResponseCache> ProviderResponseCaches => Set<ProviderResponseCache>();
        public DbSet<LinkCandidates> LinkCandidates => Set<LinkCandidates>();
        public DbSet<MuSeriesRaw> MuSeriesRaws => Set<MuSeriesRaw>();
        public DbSet<CvVolumeRaw> CvVolumeRaws => Set<CvVolumeRaw>();

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<LocgComicRaw>(e =>
            {
                e.ToTable("LocgComicRaw");
                e.HasKey(x => x.LocgComicId);
                e.Property(x => x.LocgComicId).ValueGeneratedNever();
                e.Property(x => x.IsKey).HasDefaultValue(false);
            });
            modelBuilder.Entity<LocgCreatorRaw>(e =>
            {
                e.ToTable("LocgCreatorRaw");
                e.HasKey(x => new { x.LocgComicId, x.Ordinal });
            });
            modelBuilder.Entity<LocgContainment>(e =>
            {
                e.ToTable("LocgContainment");
                e.HasKey(x => x.Id);
                e.Property(x => x.Id).ValueGeneratedNever();
                e.Property(x => x.Ordinal).HasDefaultValue(0);
                e.HasIndex(x => new { x.ContainerLocgComicId, x.ContainedLocgComicId }).IsUnique();
                e.HasIndex(x => x.ContainedLocgComicId);
            });
            modelBuilder.Entity<LocgSeries>(e =>
            {
                e.ToTable("LocgSeries");
                e.HasKey(x => x.LocgSeriesId);
                e.Property(x => x.LocgSeriesId).ValueGeneratedNever();
                e.Property(x => x.IssueCount).HasDefaultValue(0);
            });
            modelBuilder.Entity<LocgSeriesInference>(e =>
            {
                e.ToTable("LocgSeriesInference");
                e.HasKey(x => x.GcdSeriesId);
                e.Property(x => x.GcdSeriesId).ValueGeneratedNever();
                e.Property(x => x.Support).HasDefaultValue(0);
            });
            modelBuilder.Entity<GcdIssue>(e =>
            {
                e.ToTable("GcdIssue");
                e.HasKey(x => x.GcdIssueId);
                e.Property(x => x.GcdIssueId).ValueGeneratedNever();
                e.HasIndex(x => x.GcdSeriesId);
                e.HasIndex(x => x.ValidIsbn);
                e.HasIndex(x => x.Barcode);
            });
            modelBuilder.Entity<GcdSeries>(e =>
            {
                e.ToTable("GcdSeries");
                e.HasKey(x => x.GcdSeriesId);
                e.Property(x => x.GcdSeriesId).ValueGeneratedNever();
                e.Property(x => x.IssueCount).HasDefaultValue(0);
                e.Property(x => x.HasIsbn).HasDefaultValue(false);
                e.Property(x => x.HasBarcode).HasDefaultValue(false);
            });
            modelBuilder.Entity<OpenLibraryEdition>(e =>
            {
                e.ToTable("OpenLibraryEdition");
                e.HasKey(x => x.Isbn);
                e.HasIndex(x => x.OlWorkKey);
            });
            modelBuilder.Entity<OpenLibraryWork>(e =>
            {
                e.ToTable("OpenLibraryWork");
                e.HasKey(x => x.WorkKey);
                e.Property(x => x.EditionCount).HasDefaultValue(0);
            });
            modelBuilder.Entity<OlSeriesInference>(e =>
            {
                e.ToTable("OlSeriesInference");
                e.HasKey(x => x.GcdSeriesId);
                e.Property(x => x.GcdSeriesId).ValueGeneratedNever();
                e.Property(x => x.IsbnSupport).HasDefaultValue(0);
            });
            modelBuilder.Entity<MarvelSeries>(e =>
            {
                e.ToTable("MarvelSeries");
                e.HasKey(x => x.MarvelSeriesId);
                e.Property(x => x.MarvelSeriesId).ValueGeneratedNever();
            });
            modelBuilder.Entity<MarvelIssue>(e =>
            {
                e.ToTable("MarvelIssue");
                e.HasKey(x => x.MarvelIssueId);
                e.Property(x => x.MarvelIssueId).ValueGeneratedNever();
            });
            modelBuilder.Entity<MarvelSeriesLink>(e =>
            {
                e.ToTable("MarvelSeriesLink");
                e.HasKey(x => x.SeriesId);
                e.Property(x => x.SeriesId).ValueGeneratedNever();
            });
            modelBuilder.Entity<BarcodeScan>(e =>
            {
                e.ToTable("BarcodeScan");
                e.HasKey(x => x.ItemId);
                e.Property(x => x.ItemId).ValueGeneratedNever();
                e.Property(x => x.PagesScanned).HasDefaultValue(0);
            });
            modelBuilder.Entity<ProviderResponseCache>(e =>
            {
                e.ToTable("ProviderResponseCache");
                e.HasKey(x => new { x.Provider, x.RequestKey });
            });
            modelBuilder.Entity<LinkCandidates>(e =>
            {
                e.ToTable("LinkCandidates");
                e.HasKey(x => new { x.Scope, x.Key, x.Provider });
            });
            modelBuilder.Entity<MuSeriesRaw>(e =>
            {
                e.ToTable("MuSeriesRaw");
                e.HasKey(x => x.MuSeriesId);
                e.Property(x => x.MuSeriesId).ValueGeneratedNever();
            });
            modelBuilder.Entity<CvVolumeRaw>(e =>
            {
                e.ToTable("CvVolumeRaw");
                e.HasKey(x => x.CvVolumeId);
                e.Property(x => x.CvVolumeId).ValueGeneratedNever();
            });
        }
    }
}
