// <auto-generated> by scripts/books/gen/gen_entities.py from docs/books/v2-mapping.json — do not edit by hand.
namespace MovieTheater.Books.Db
{
    /// <summary>Stored as int. Vocabulary from v2-mapping.json enums["Item.Kind"].</summary>
    public enum ItemKind { Comic = 0, Book = 1 }
    /// <summary>Stored as int. Vocabulary from v2-mapping.json enums["Item.ContainerFormat"].</summary>
    public enum ContainerFormat { Cbz = 0, Cbr = 1, Pdf = 2, Epub = 3, Mobi = 4, Unknown = 5 }
    /// <summary>Stored as int. Vocabulary from v2-mapping.json enums["ComicDetail.Format"].</summary>
    public enum ComicFormat { SingleIssue = 0, Tpb = 1, Hardcover = 2, Omnibus = 3, Annual = 4, Special = 5, OneShot = 6, GraphicNovel = 7, LimitedSeries = 8, Weekly = 9, Reprint = 10, Collection = 11, Magazine = 12, Unknown = 13 }
    /// <summary>Stored as int. Vocabulary from v2-mapping.json enums["Confidence"].</summary>
    public enum Confidence { Unknown = 0, Low = 1, Medium = 2, High = 3 }
    /// <summary>Stored as int. Vocabulary from v2-mapping.json enums["ComicDetail.*Source"].</summary>
    public enum ParseSource { None = 0, Metadata = 1, MetadataAlt = 2, Filename = 3, FilenameLeadingIndex = 4, Folder = 5, Volume = 6, Default = 7, Manual = 8 }
    /// <summary>Stored as int. Vocabulary from v2-mapping.json enums["ReadingOrderEntry.Source"].</summary>
    public enum ReadingOrderSource { Unordered = 0, ComicVine = 1, Date = 2, IssueNo = 3, IssueNoDate = 4, ClaudeYear = 5, IssueNoClaudeYear = 6, Containment = 7 }
    /// <summary>Stored as int. Vocabulary from v2-mapping.json enums["DatePrecision"].</summary>
    public enum DatePrecision { None = 0, Year = 1, Month = 2, Day = 3 }
    /// <summary>Stored as int. Vocabulary from v2-mapping.json enums["CollectionNode.Level"].</summary>
    public enum CollectionLevel { Issue = 0, Volume = 1, Book = 2, Omnibus = 3 }
    /// <summary>Stored as int. Vocabulary from v2-mapping.json enums["CollectionNode.TrackRole"].</summary>
    public enum TrackRole { Primary = 0, Container = 1, Alternate = 2 }
    /// <summary>Stored as int. Vocabulary from v2-mapping.json enums["CollectionNode.SpanSource"].</summary>
    public enum SpanSource { None = 0, Inferred = 1, ComicVine = 2, Gcd = 3, Locg = 4, Curated = 5 }
    /// <summary>Stored as int. Vocabulary from v2-mapping.json enums["Provider"].</summary>
    public enum Provider { Cv = 0, External = 1, Locg = 2, Gcd = 3, Mu = 4, Barney = 5, Marvel = 6, Inducks = 7 }
    /// <summary>Stored as int. Vocabulary from v2-mapping.json enums["LinkStatus"].</summary>
    public enum LinkStatus { Pending = 0, Matched = 1, NoMatch = 2, Multiple = 3, Error = 4, Manual = 5, Cleared = 6, Skip = 7 }
    /// <summary>Stored as int. Vocabulary from v2-mapping.json enums["LinkQuality"].</summary>
    public enum LinkQuality { Unknown = 0, Low = 1, Medium = 2, High = 3, Conflict = 4 }
    /// <summary>Stored as int. Vocabulary from v2-mapping.json enums["CollectedEditionSpan.Source"].</summary>
    public enum EditionSource { Locg = 0, Gcd = 1, Cv = 2, Curated = 3 }
    /// <summary>Stored as int. Vocabulary from v2-mapping.json enums["Insight.SubjectKind / Rating.TargetKind"].</summary>
    public enum SubjectKind { Item = 0, Series = 1 }
    /// <summary>Stored as int. Vocabulary from v2-mapping.json enums["Rating.Source"].</summary>
    public enum RatingSource { User = 0, AI = 1, Locg = 2, Mu = 3, Library = 4, Override = 5 }
    /// <summary>Stored as int. Vocabulary from v2-mapping.json enums["ItemCredit.Source / ItemTag.Source"].</summary>
    public enum TagSource { ComicInfo = 0, Cv = 1, Calibre = 2, Locg = 3, Gcd = 4, External = 5, Mu = 6, AI = 7 }
    /// <summary>Stored as int. Vocabulary from v2-mapping.json enums["UserItemState.Status"].</summary>
    public enum ReadStatus { Unread = 0, InProgress = 1, Finished = 2 }
    /// <summary>Stored as int. Vocabulary from v2-mapping.json enums["GroupMark.GroupType"].</summary>
    public enum GroupType { Series = 0, Volume = 1, Collection = 2, Publisher = 3, Decade = 4 }
    /// <summary>Stored as int. Vocabulary from v2-mapping.json enums["Item.ResolvedSynopsisSource"].</summary>
    public enum SynopsisSource { None = 0, Cv = 1, Embedded = 2, Locg = 3, External = 4, Mu = 5, CvDeck = 6, AI = 7 }
}
