// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieTheater.Db;

#nullable disable

namespace MovieTheater.Db.Migrations
{
    [DbContext(typeof(MovieDb))]
    [Migration("20260616152411_AddMiscVideo")]
    partial class AddMiscVideo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieTheater.Db.Boardgame", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal?>("AverageRating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AverageWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BaseGameId")
                        .HasColumnType("int");

                    b.Property<decimal?>("BayesAverageRating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BggThingId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HowToPlayVideoUrlsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSyncedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaxPlayTime")
                        .HasColumnType("int");

                    b.Property<int?>("MaxPlayers")
                        .HasColumnType("int");

                    b.Property<decimal?>("Median")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MinAge")
                        .HasColumnType("int");

                    b.Property<int?>("MinPlayTime")
                        .HasColumnType("int");

                    b.Property<int?>("MinPlayers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumComments")
                        .HasColumnType("int");

                    b.Property<int?>("NumWeights")
                        .HasColumnType("int");

                    b.Property<int?>("Owned")
                        .HasColumnType("int");

                    b.Property<int?>("PlayingTime")
                        .HasColumnType("int");

                    b.Property<string>("RulesPdfCandidateUrlsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RulesPdfUrlsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RulesSyncedUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("StdDev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ThingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Trading")
                        .HasColumnType("int");

                    b.Property<int?>("UsersRated")
                        .HasColumnType("int");

                    b.Property<int?>("Wanting")
                        .HasColumnType("int");

                    b.Property<int?>("Wishing")
                        .HasColumnType("int");

                    b.Property<int?>("YearPublished")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("BaseGameId");

                    b.HasIndex("BggThingId")
                        .IsUnique();

                    b.ToTable("Boardgame");
                });

            modelBuilder.Entity("MovieTheater.Db.BoardgameExtraDetails", b =>
                {
                    b.Property<int>("BoardgameId")
                        .HasColumnType("int");

                    b.Property<string>("AlternateNamesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinksJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarketplaceXml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PollsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RanksJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawXml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SimilarGamesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VersionsXml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideosJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BoardgameId");

                    b.ToTable("BoardgameExtraDetails");
                });

            modelBuilder.Entity("MovieTheater.Db.BoardgameImageDetails", b =>
                {
                    b.Property<int>("BoardgameId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImageVersion")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BoardgameId");

                    b.ToTable("BoardgameImageDetails");
                });

            modelBuilder.Entity("MovieTheater.Db.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AnchorUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("FilterJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Seed")
                        .HasColumnType("int");

                    b.Property<string>("ShuffleMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Channel");
                });

            modelBuilder.Entity("MovieTheater.Db.ChannelScheduleItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayableId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlayableId");

                    b.HasIndex("ChannelId", "StartUtc");

                    b.ToTable("ChannelScheduleItem");
                });

            modelBuilder.Entity("MovieTheater.Db.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AirDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("int");

                    b.Property<string>("ImdbId")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal?>("ImdbRating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PlayableId")
                        .HasColumnType("int");

                    b.Property<string>("Plot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("int");

                    b.Property<int>("SeriesMovieId")
                        .HasColumnType("int");

                    b.Property<string>("StillPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("PlayableId")
                        .IsUnique()
                        .HasFilter("[PlayableId] IS NOT NULL");

                    b.HasIndex("SeriesMovieId", "SeasonNumber", "EpisodeNumber")
                        .IsUnique();

                    b.ToTable("Episode");
                });

            modelBuilder.Entity("MovieTheater.Db.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genre");
                });

            modelBuilder.Entity("MovieTheater.Db.MediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AudioChannels")
                        .HasColumnType("int");

                    b.Property<string>("AudioCodec")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("AudioLayout")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("BitDepth")
                        .HasColumnType("int");

                    b.Property<string>("Container")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long?>("DurationTicks")
                        .HasColumnType("bigint");

                    b.Property<double?>("FrameRate")
                        .HasColumnType("float");

                    b.Property<string>("HdrFormat")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<bool?>("IsHdr")
                        .HasColumnType("bit");

                    b.Property<string>("JellyfinItemId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Label")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("LastSyncedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MissingSinceUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PartNumber")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("PlayableId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("VideoCodec")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayableId");

                    b.ToTable("MediaFile");
                });

            modelBuilder.Entity("MovieTheater.Db.MiscVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CollectionName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayableId")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedMovieId")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedSeriesId")
                        .HasColumnType("int");

                    b.Property<string>("ReviewBatch")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ReviewProvenance")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ReviewSourcePath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("SimpleTitle")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollectionName");

                    b.HasIndex("PlayableId")
                        .IsUnique();

                    b.HasIndex("RelatedMovieId");

                    b.HasIndex("RelatedSeriesId");

                    b.HasIndex("ReviewBatch");

                    b.ToTable("MiscVideo");
                });

            modelBuilder.Entity("MovieTheater.Db.Movie", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Actors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackdropPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("BudgetUsd")
                        .HasColumnType("bigint");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ImdbNeedsReview")
                        .HasColumnType("bit");

                    b.Property<decimal?>("ImdbRatingScraped")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ImdbReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImdbReviewReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImdbScrapedTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ImdbVerifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MpaaRating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlayableId")
                        .HasColumnType("int");

                    b.Property<string>("Plot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlotFull")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlotSynopsis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RemoveFromRandom")
                        .HasColumnType("bit");

                    b.Property<long?>("RevenueUsd")
                        .HasColumnType("bigint");

                    b.Property<string>("ReviewBatch")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ReviewConfidence")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("ReviewProvenance")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ReviewSourcePath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<bool>("RtNeedsReview")
                        .HasColumnType("bit");

                    b.Property<int?>("RtPopcornmeter")
                        .HasColumnType("int");

                    b.Property<string>("RtReviewReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RtScoresUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RtTomatometer")
                        .HasColumnType("int");

                    b.Property<string>("RtUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Runtime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("SimpleTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tagline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TitleType")
                        .HasColumnType("int");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TmdbPopularity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TmdbVoteCount")
                        .HasColumnType("int");

                    b.Property<string>("TopCast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrailerKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Writer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imdbID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("imdbRating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("tomatoRating")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("PlayableId")
                        .IsUnique()
                        .HasFilter("[PlayableId] IS NOT NULL");

                    b.HasIndex("ReviewBatch");

                    b.ToTable("Movie");
                });

            modelBuilder.Entity("MovieTheater.Db.MovieCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Character")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.Property<int>("Ordering")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("MovieID", "PersonId", "Role")
                        .IsUnique();

                    b.ToTable("MovieCredit");
                });

            modelBuilder.Entity("MovieTheater.Db.MovieGenre", b =>
                {
                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("Ordering")
                        .HasColumnType("int");

                    b.HasKey("MovieID", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MovieGenre");
                });

            modelBuilder.Entity("MovieTheater.Db.MoviePlaybackProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<long>("DurationTicks")
                        .HasColumnType("bigint");

                    b.Property<int>("PlayableId")
                        .HasColumnType("int");

                    b.Property<long>("PositionTicks")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayableId");

                    b.HasIndex("UserID", "PlayableId")
                        .IsUnique();

                    b.ToTable("MoviePlaybackProgress");
                });

            modelBuilder.Entity("MovieTheater.Db.MoviePlotSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.Property<int>("Ordering")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MovieID");

                    b.ToTable("MoviePlotSummary");
                });

            modelBuilder.Entity("MovieTheater.Db.MoviePosterDetails", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("DominantColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PosterVersion")
                        .HasColumnType("int");

                    b.HasKey("MovieId");

                    b.ToTable("MoviePosterDetails");
                });

            modelBuilder.Entity("MovieTheater.Db.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImdbNameId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NameKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PrimaryProfessions")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ImdbNameId")
                        .IsUnique()
                        .HasFilter("[ImdbNameId] IS NOT NULL");

                    b.HasIndex("NameKey");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("MovieTheater.Db.Playable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Playable");
                });

            modelBuilder.Entity("MovieTheater.Db.RatingMPA", b =>
                {
                    b.Property<int>("RatingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingID"));

                    b.Property<string>("MPAName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinAge")
                        .HasColumnType("int");

                    b.HasKey("RatingID");

                    b.ToTable("RatingMPA");
                });

            modelBuilder.Entity("MovieTheater.Db.RatingMap", b =>
                {
                    b.Property<int>("RatingMapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingMapID"));

                    b.Property<int>("MPARatingID")
                        .HasColumnType("int");

                    b.Property<string>("MovieRating")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RatingMapID");

                    b.ToTable("RatingMap");
                });

            modelBuilder.Entity("MovieTheater.Db.Series", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int?>("EndYear")
                        .HasColumnType("int");

                    b.Property<int?>("EpisodeCount")
                        .HasColumnType("int");

                    b.Property<string>("Network")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("SeasonCount")
                        .HasColumnType("int");

                    b.Property<int?>("StartYear")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("MovieId");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("MovieTheater.Db.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MovieTheater.Db.UserSettings", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("MovieTheater.Db.Viewing", b =>
                {
                    b.Property<int>("ViewingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ViewingID"));

                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("ViewingData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViewingType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ViewingID");

                    b.HasIndex("MovieID");

                    b.HasIndex("UserID");

                    b.ToTable("Viewing");
                });

            modelBuilder.Entity("MovieTheater.Db.Boardgame", b =>
                {
                    b.HasOne("MovieTheater.Db.Boardgame", "BaseGame")
                        .WithMany("Expansions")
                        .HasForeignKey("BaseGameId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseGame");
                });

            modelBuilder.Entity("MovieTheater.Db.BoardgameExtraDetails", b =>
                {
                    b.HasOne("MovieTheater.Db.Boardgame", null)
                        .WithOne("ExtraDetails")
                        .HasForeignKey("MovieTheater.Db.BoardgameExtraDetails", "BoardgameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieTheater.Db.BoardgameImageDetails", b =>
                {
                    b.HasOne("MovieTheater.Db.Boardgame", "Boardgame")
                        .WithOne("ImageDetails")
                        .HasForeignKey("MovieTheater.Db.BoardgameImageDetails", "BoardgameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boardgame");
                });

            modelBuilder.Entity("MovieTheater.Db.ChannelScheduleItem", b =>
                {
                    b.HasOne("MovieTheater.Db.Channel", "Channel")
                        .WithMany("ScheduleItems")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieTheater.Db.Playable", "Playable")
                        .WithMany()
                        .HasForeignKey("PlayableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Playable");
                });

            modelBuilder.Entity("MovieTheater.Db.Episode", b =>
                {
                    b.HasOne("MovieTheater.Db.Playable", "Playable")
                        .WithOne()
                        .HasForeignKey("MovieTheater.Db.Episode", "PlayableId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MovieTheater.Db.Movie", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesMovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playable");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("MovieTheater.Db.MediaFile", b =>
                {
                    b.HasOne("MovieTheater.Db.Playable", "Playable")
                        .WithMany("Files")
                        .HasForeignKey("PlayableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playable");
                });

            modelBuilder.Entity("MovieTheater.Db.MiscVideo", b =>
                {
                    b.HasOne("MovieTheater.Db.Playable", "Playable")
                        .WithOne()
                        .HasForeignKey("MovieTheater.Db.MiscVideo", "PlayableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovieTheater.Db.Movie", "RelatedMovie")
                        .WithMany()
                        .HasForeignKey("RelatedMovieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MovieTheater.Db.Series", "RelatedSeries")
                        .WithMany()
                        .HasForeignKey("RelatedSeriesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Playable");

                    b.Navigation("RelatedMovie");

                    b.Navigation("RelatedSeries");
                });

            modelBuilder.Entity("MovieTheater.Db.Movie", b =>
                {
                    b.HasOne("MovieTheater.Db.Playable", "Playable")
                        .WithOne()
                        .HasForeignKey("MovieTheater.Db.Movie", "PlayableId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Playable");
                });

            modelBuilder.Entity("MovieTheater.Db.MovieCredit", b =>
                {
                    b.HasOne("MovieTheater.Db.Movie", "Movie")
                        .WithMany("Credits")
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieTheater.Db.Person", "Person")
                        .WithMany("Credits")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MovieTheater.Db.MovieGenre", b =>
                {
                    b.HasOne("MovieTheater.Db.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieTheater.Db.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieTheater.Db.MoviePlaybackProgress", b =>
                {
                    b.HasOne("MovieTheater.Db.Playable", "Playable")
                        .WithMany()
                        .HasForeignKey("PlayableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieTheater.Db.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Playable");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieTheater.Db.MoviePlotSummary", b =>
                {
                    b.HasOne("MovieTheater.Db.Movie", "Movie")
                        .WithMany("PlotSummaries")
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieTheater.Db.MoviePosterDetails", b =>
                {
                    b.HasOne("MovieTheater.Db.Movie", "Movie")
                        .WithOne("PosterDetails")
                        .HasForeignKey("MovieTheater.Db.MoviePosterDetails", "MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieTheater.Db.Series", b =>
                {
                    b.HasOne("MovieTheater.Db.Movie", "Movie")
                        .WithOne()
                        .HasForeignKey("MovieTheater.Db.Series", "MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieTheater.Db.UserSettings", b =>
                {
                    b.HasOne("MovieTheater.Db.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieTheater.Db.Viewing", b =>
                {
                    b.HasOne("MovieTheater.Db.Movie", "Movie")
                        .WithMany("Viewings")
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieTheater.Db.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieTheater.Db.Boardgame", b =>
                {
                    b.Navigation("Expansions");

                    b.Navigation("ExtraDetails");

                    b.Navigation("ImageDetails");
                });

            modelBuilder.Entity("MovieTheater.Db.Channel", b =>
                {
                    b.Navigation("ScheduleItems");
                });

            modelBuilder.Entity("MovieTheater.Db.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("MovieTheater.Db.Movie", b =>
                {
                    b.Navigation("Credits");

                    b.Navigation("MovieGenres");

                    b.Navigation("PlotSummaries");

                    b.Navigation("PosterDetails");

                    b.Navigation("Viewings");
                });

            modelBuilder.Entity("MovieTheater.Db.Person", b =>
                {
                    b.Navigation("Credits");
                });

            modelBuilder.Entity("MovieTheater.Db.Playable", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
