// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieTheater.Db;

#nullable disable

namespace MovieTheater.Db.Migrations
{
    [DbContext(typeof(MovieDb))]
    [Migration("20260610175738_AddNormalizedImdbData")]
    partial class AddNormalizedImdbData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieTheater.Db.Boardgame", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal?>("AverageRating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AverageWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BaseGameId")
                        .HasColumnType("int");

                    b.Property<decimal?>("BayesAverageRating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BggThingId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HowToPlayVideoUrlsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSyncedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaxPlayTime")
                        .HasColumnType("int");

                    b.Property<int?>("MaxPlayers")
                        .HasColumnType("int");

                    b.Property<decimal?>("Median")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MinAge")
                        .HasColumnType("int");

                    b.Property<int?>("MinPlayTime")
                        .HasColumnType("int");

                    b.Property<int?>("MinPlayers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumComments")
                        .HasColumnType("int");

                    b.Property<int?>("NumWeights")
                        .HasColumnType("int");

                    b.Property<int?>("Owned")
                        .HasColumnType("int");

                    b.Property<int?>("PlayingTime")
                        .HasColumnType("int");

                    b.Property<string>("RulesPdfCandidateUrlsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RulesPdfUrlsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RulesSyncedUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("StdDev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ThingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Trading")
                        .HasColumnType("int");

                    b.Property<int?>("UsersRated")
                        .HasColumnType("int");

                    b.Property<int?>("Wanting")
                        .HasColumnType("int");

                    b.Property<int?>("Wishing")
                        .HasColumnType("int");

                    b.Property<int?>("YearPublished")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("BaseGameId");

                    b.HasIndex("BggThingId")
                        .IsUnique();

                    b.ToTable("Boardgame");
                });

            modelBuilder.Entity("MovieTheater.Db.BoardgameExtraDetails", b =>
                {
                    b.Property<int>("BoardgameId")
                        .HasColumnType("int");

                    b.Property<string>("AlternateNamesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinksJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarketplaceXml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PollsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RanksJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawXml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VersionsXml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideosJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BoardgameId");

                    b.ToTable("BoardgameExtraDetails");
                });

            modelBuilder.Entity("MovieTheater.Db.BoardgameImageDetails", b =>
                {
                    b.Property<int>("BoardgameId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImageVersion")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BoardgameId");

                    b.ToTable("BoardgameImageDetails");
                });

            modelBuilder.Entity("MovieTheater.Db.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genre");
                });

            modelBuilder.Entity("MovieTheater.Db.Movie", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Actors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ImdbNeedsReview")
                        .HasColumnType("bit");

                    b.Property<decimal?>("ImdbRatingScraped")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ImdbReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImdbReviewReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImdbScrapedTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ImdbVerifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MpaaRating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlotFull")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RemoveFromRandom")
                        .HasColumnType("bit");

                    b.Property<string>("Runtime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("SimpleTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Writer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imdbID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("imdbRating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("tomatoRating")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Movie");
                });

            modelBuilder.Entity("MovieTheater.Db.MovieCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Character")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.Property<int>("Ordering")
                        .HasColumnType("int");

                    b.Property<string>("PersonImdbNameId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonImdbNameId");

                    b.HasIndex("MovieID", "PersonImdbNameId", "Role")
                        .IsUnique();

                    b.ToTable("MovieCredit");
                });

            modelBuilder.Entity("MovieTheater.Db.MovieGenre", b =>
                {
                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("Ordering")
                        .HasColumnType("int");

                    b.HasKey("MovieID", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MovieGenre");
                });

            modelBuilder.Entity("MovieTheater.Db.MoviePosterDetails", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("DominantColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PosterVersion")
                        .HasColumnType("int");

                    b.HasKey("MovieId");

                    b.ToTable("MoviePosterDetails");
                });

            modelBuilder.Entity("MovieTheater.Db.Person", b =>
                {
                    b.Property<string>("ImdbNameId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryProfessions")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImdbNameId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("MovieTheater.Db.RatingMPA", b =>
                {
                    b.Property<int>("RatingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingID"));

                    b.Property<string>("MPAName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinAge")
                        .HasColumnType("int");

                    b.HasKey("RatingID");

                    b.ToTable("RatingMPA");
                });

            modelBuilder.Entity("MovieTheater.Db.RatingMap", b =>
                {
                    b.Property<int>("RatingMapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingMapID"));

                    b.Property<int>("MPARatingID")
                        .HasColumnType("int");

                    b.Property<string>("MovieRating")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RatingMapID");

                    b.ToTable("RatingMap");
                });

            modelBuilder.Entity("MovieTheater.Db.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MovieTheater.Db.UserSettings", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("MovieTheater.Db.Viewing", b =>
                {
                    b.Property<int>("ViewingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ViewingID"));

                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("ViewingData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViewingType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ViewingID");

                    b.HasIndex("MovieID");

                    b.HasIndex("UserID");

                    b.ToTable("Viewing");
                });

            modelBuilder.Entity("MovieTheater.Db.Boardgame", b =>
                {
                    b.HasOne("MovieTheater.Db.Boardgame", "BaseGame")
                        .WithMany("Expansions")
                        .HasForeignKey("BaseGameId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseGame");
                });

            modelBuilder.Entity("MovieTheater.Db.BoardgameExtraDetails", b =>
                {
                    b.HasOne("MovieTheater.Db.Boardgame", null)
                        .WithOne("ExtraDetails")
                        .HasForeignKey("MovieTheater.Db.BoardgameExtraDetails", "BoardgameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieTheater.Db.BoardgameImageDetails", b =>
                {
                    b.HasOne("MovieTheater.Db.Boardgame", "Boardgame")
                        .WithOne("ImageDetails")
                        .HasForeignKey("MovieTheater.Db.BoardgameImageDetails", "BoardgameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boardgame");
                });

            modelBuilder.Entity("MovieTheater.Db.MovieCredit", b =>
                {
                    b.HasOne("MovieTheater.Db.Movie", "Movie")
                        .WithMany("Credits")
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieTheater.Db.Person", "Person")
                        .WithMany("Credits")
                        .HasForeignKey("PersonImdbNameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MovieTheater.Db.MovieGenre", b =>
                {
                    b.HasOne("MovieTheater.Db.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieTheater.Db.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieTheater.Db.MoviePosterDetails", b =>
                {
                    b.HasOne("MovieTheater.Db.Movie", "Movie")
                        .WithOne("PosterDetails")
                        .HasForeignKey("MovieTheater.Db.MoviePosterDetails", "MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieTheater.Db.UserSettings", b =>
                {
                    b.HasOne("MovieTheater.Db.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieTheater.Db.Viewing", b =>
                {
                    b.HasOne("MovieTheater.Db.Movie", "Movie")
                        .WithMany("Viewings")
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieTheater.Db.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieTheater.Db.Boardgame", b =>
                {
                    b.Navigation("Expansions");

                    b.Navigation("ExtraDetails");

                    b.Navigation("ImageDetails");
                });

            modelBuilder.Entity("MovieTheater.Db.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("MovieTheater.Db.Movie", b =>
                {
                    b.Navigation("Credits");

                    b.Navigation("MovieGenres");

                    b.Navigation("PosterDetails");

                    b.Navigation("Viewings");
                });

            modelBuilder.Entity("MovieTheater.Db.Person", b =>
                {
                    b.Navigation("Credits");
                });
#pragma warning restore 612, 618
        }
    }
}
