apiVersion: v1
kind: PersistentVolume
metadata:
  name: movietheater-volume
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  capacity:
    - storage: 10Gi
  hostPath:
    path: "/movietheater/volume"
