# Build react app
FROM node:20-alpine AS reactapp-build
WORKDIR /build
COPY src/ui/package.json .
COPY src/ui/package-lock.json .
RUN npm install
COPY src/ui/ .
RUN npm run build

# Build final release image
FROM node:20-alpine AS release
RUN npm install -g serve

WORKDIR /app
COPY --from=reactapp-build /build/build .

# serve -s /app -l 3000
CMD ["serve", "-s", "/app", "-l", "3000"]
