using System;
using System.Collections.Generic;

namespace MovieTheater.Arcade
{
    /// <summary>
    /// Hand-curated box-art aliases: cards whose Title differs from the libretro-thumbnails filename in a
    /// way the automatic matcher (exact name, tag-stripped title, token signature) can't bridge — a
    /// publisher prefix ("Disney's ..."), an appended subtitle ("Wave Race 64 - Kawasaki Jet Ski"), a word
    /// substitution ("Kobe Bryant's" -> "Kobe Bryant in"), or a spelled-out/extra token ("Quake 64" ->
    /// "Quake"). Generated by `arcade-boxart --report-misses` + review; most were auto-derived by the
    /// contiguous-token rule, a few hand-verified. Key = "{system}|{Normalize(Title)}"; value = the exact
    /// libretro filename (no .png). The matcher tries the alias FIRST. Add rows here as new gaps surface.
    /// </summary>
    public static class ArcadeBoxArtAliases
    {
        public static readonly Dictionary<string, string> Map = new(StringComparer.Ordinal)
        {
            ["a2600|homerun"] = "Home Run - Baseball (USA)",
            ["a2600|mazecrazeagameofcopsnrobbers"] = "Maze Craze - A Game of Cops 'n Robbers - Maze Mania - A Game of Cops 'n Robbers (USA)",
            ["a2600|miniaturegolf"] = "Miniature Golf - Arcade Golf (USA)",
            ["a2600|rainbowinvaders"] = "Rainbow Invaders v0.99 (2006-02-20)(Mogno, Silvio)(NTSC)(PD)",
            ["a2600|skydiver"] = "Sky Diver - Dare Diver (USA)",
            ["a2600|slotmachine"] = "Slot Machine - Slots (USA)",
            ["a2600|slotracers"] = "Slot Racers - Maze (USA)",
            ["a2600|starship"] = "Star Ship - Outer Space (USA)",
            ["a2600|streetracer"] = "Street Racer - Speedway II (USA)",
            ["a2600|trackfield"] = "Track and Field (USA)",
            ["dc|buzzlightyearofstarcommand"] = "Disney-Pixar Buzz Lightyear of Star Command (USA)",
            ["dc|donaldduckgoinquackers"] = "Disney's Donald Duck - Goin' Quackers (USA)",
            ["dc|metropolisstreetracer"] = "MSR - Metropolis Street Racer (USA) (Rev A)",
            ["dc|tomclancysrainbowsixroguespear"] = "Tom Clancy's Rainbow Six - Rogue Spear + Mission Pack - Urban Operations (USA)",
            ["dc|toystory2buzzlightyeartotherescue"] = "Disney-Pixar Toy Story 2 - Buzz Lightyear to the Rescue! (USA)",
            ["gb|doubledragon3"] = "Double Dragon 3 - The Arcade Game (USA, Europe)",
            ["gb|fightingsimulator2in1"] = "Fighting Simulator 2 in 1 - Flying Warriors (USA, Europe)",
            ["gb|getawaythe"] = "Getaway, The - High Speed II (USA)",
            ["gb|hittheice"] = "Hit the Ice - VHL - The Official Video Hockey League (USA, Europe)",
            ["gb|jeepjamboree"] = "Jeep Jamboree - Off-Road Adventure (USA)",
            ["gb|mauimallard"] = "Maui Mallard in Cold Shadow (USA)",
            ["gb|miner2049er"] = "Miner 2049er Starring Bounty Bob (USA)",
            ["gb|parasolstars"] = "Parasol Stars - Rainbow Islands II (Europe)",
            ["gb|spidermanxmen"] = "Spider-Man - X-Men - Arcade's Revenge (USA, Europe)",
            ["gb|turnandburn"] = "Turn and Burn - The F-14 Dogfight Simulator (USA)",
            ["gba|alexfergusonsplayermanager2002"] = "Alex Ferguson's Player Manager 2002 ~ Total Soccer Manager (Europe) (En,Fr,De,Es,It,Nl)",
            ["gba|barbiesuperpack"] = "Barbie Superpack - Secret Agent + Groovy Games (USA)",
            ["gba|crashsuperpack"] = "Crash Superpack - Crash Bandicoot 2 - N-Tranced + Crash Nitro Kart (USA)",
            ["gba|hobbitthe"] = "Hobbit, The - The Prelude to the Lord of the Rings (USA)",
            ["gba|rippingfriendsthe"] = "Ripping Friends, The - The World's Most Manly Men! (USA, Europe)",
            ["gba|spyrosuperpack"] = "Spyro Superpack - Spyro - Season of Ice + Spyro 2 - Season of Flame (USA)",
            ["gba|zidanefootballgeneration"] = "Zidane Football Generation 2002 (Europe) (En,Fr,De,Es,It)",
            ["gbc|bearinthebigbluehouse"] = "Jim Henson's Bear in the Big Blue House (USA) (En,Fr,De,Es,It,Nl)",
            ["gbc|elmos123s"] = "Sesame Street - Elmo's 123s (USA) (GB Compatible)",
            ["gbc|elmosabcs"] = "Sesame Street - Elmo's ABCs (USA) (GB Compatible)",
            ["gbc|f1worldgrandprixii"] = "F1 World Grand Prix II for Game Boy Color (USA) (En,Fr,De,Es)",
            ["gbc|powerrangerslightspeedrescue"] = "Saban's Power Rangers - Lightspeed Rescue (USA, Europe)",
            ["gbc|powerrangerstimeforce"] = "Saban's Power Rangers - Time Force (USA, Europe)",
            ["gbc|tomjerry"] = "Tom and Jerry (USA, Europe)",
            ["gbc|totalsoccer2000"] = "David O'Leary's Total Soccer 2000 (Europe) (En,Fr,De,Es,It,Nl)",
            ["gbc|worlddestructionleaguethundertanks"] = "WDL - World Destruction League - Thunder Tanks (USA) (Beta)",
            ["genesis|bareknuckleii"] = "Bare Knuckle II - Shitou e no Requiem ~ Streets of Rage II (Japan, Europe)",
            ["genesis|magicschoolbusthe"] = "Magic School Bus, The - Space Exploration Game (USA)",
            ["genesis|nbaprobasketballbullsvslakers"] = "NBA Pro Basketball - Bulls vs Lakers and the NBA Playoffs (Japan)",
            ["gg|archrivals"] = "Arch Rivals - The Arcade Game (USA)",
            ["gg|bakubakuanimal"] = "Baku Baku Animal - Sekai Shiikugakari Senshu-ken (Japan)",
            ["gg|bartmanmeetsradioactiveman"] = "Simpsons, The - Bartman Meets Radioactive Man (USA)",
            ["gg|cocacolakid"] = "Sassou Shounen Eiyuuden - Coca-Cola Kid (Japan)",
            ["gg|sensiblesoccer"] = "Sensible Soccer - European Champions (Europe)",
            ["gg|tailsadventures"] = "Tails Adventure ~ Tails Adventures (en-ja)[b2]",
            ["n64|elmosletteradventure"] = "Sesame Street - Elmo's Letter Adventure (USA)",
            ["n64|elmosnumberjourney"] = "Sesame Street - Elmo's Number Journey (USA)",
            ["n64|getterlovechorenaipartygame"] = "Getter Love!! - Cho Renai Party Game Tanjou (Japan)",
            ["n64|waverace64"] = "Wave Race 64 - Kawasaki Jet Ski (USA)",
            ["nes|galaxy5000"] = "Galaxy 5000 - Racing in the 51st Century (USA)",
            ["nes|happilyeverafter"] = "Happily Ever After starring Snow White (USA) (Proto)",
            ["nes|kingofkingsthe"] = "King of Kings, The - The Early Years (USA) (v1.1) (Unl)",
            ["nes|kyoutohananomisshitsusatsujinjiken"] = "Yamamura Misa Suspense - Kyouto Hana no Misshitsu Satsujin Jiken (1989-02-11)(Taito)(JP)",
            ["nes|kyoutoryuunoterasatsujinjiken"] = "Yamamura Misa Suspense - Kyouto Ryuu no Tera Satsujin Jiken (1987-12-11)(Taito)(JP)",
            ["nes|mariobrosclassic"] = "Mario Bros. - Classic Serie (1993)(Nintendo)(EU)",
            ["nes|ninjahattorikunninjawasyugyoudegozaru"] = "Ninja Hattori-kun - Ninja wa Syugyou de Gozaru no Maki (Japan)",
            ["nes|pokeriii"] = "Poker III - 5 in 1 (1991)(Sachen)(TW)[p][TC-020]",
            ["nes|raceamerica"] = "Alex DeMeo's Race America (USA)",
            ["nes|racermatechallengeii"] = "RacerMate - Challenge II v6.02.002 (1995)(RacerMate)(Computrainer)(US)",
            ["nes|realplayerspak"] = "HES 6-Pak - Real Player's Pak (Australia) (Unl)",
            ["nes|safetyrally"] = "Yasuda Fire _ Marine - Safety Rally (Japan) (Not For Resale)",
            ["nes|weilaixiaozi"] = "Wei Lai Xiao Zi - Joy Van Kid (Asia) (En) (Unl)",
            ["ngpc|baseballstarscolor"] = "Baseball Stars Color - Pocket Sports Series (World) (En,Ja)",
            ["pce|orderofthegriffon"] = "Dungeons _ Dragons - Order of the Griffon (USA)",
            ["pce|panzakickboxing"] = "Andre Panza Kick Boxing (USA)",
            ["pce|shiryousensen"] = "Shiryou Sensen - War of the Dead (Japan)",
            ["pce|specialcriminalinvestigation"] = "S.C.I. - Special Criminal Investigation (Japan)",
            ["ps1|bluesbigmusical"] = "Blue's Clues - Blue's Big Musical (USA)",
            ["ps1|couriercrisis"] = "Courier Crisis - The Saga of the Modern Fatalist (USA)",
            ["ps1|doratheexplorerbarnyardbuddies"] = "Nick Jr. Dora the Explorer - Barnyard Buddies (USA)",
            ["ps1|mechwarrior231stcenturycombat"] = "MechWarrior 2 - 31st Century Combat - Arcade Combat Edition (USA)",
            ["ps1|pacmanworld"] = "Pac-Man World - 20th Anniversary (USA)",
            ["ps1|powerrangerslightspeedrescue"] = "Saban's Power Rangers - Lightspeed Rescue (USA)",
            ["ps1|powerrangerstimeforce"] = "Saban's Power Rangers - Time Force (USA)",
            ["ps1|powerrangerszeofulltiltbattlepinball"] = "Saban's Power Rangers Zeo - Full Tilt Battle Pinball (USA)",
            ["ps1|revolutionx"] = "Revolution X - Music Is the Weapon (USA)",
            ["ps1|rocketpowerteamrocketrescue"] = "Nickelodeon Rocket Power - Team Rocket Rescue (USA)",
            ["ps1|rugratssearchforreptar"] = "Nickelodeon Rugrats - Search for Reptar (USA)",
            ["ps1|rugratsstudiotour"] = "Nickelodeon Rugrats - Studio Tour (USA)",
            ["ps1|rugratstotallyangelica"] = "Nickelodeon Rugrats - Totally Angelica (USA)",
            ["ps1|rugratsinparisthemovie"] = "Nickelodeon Rugrats in Paris - The Movie (USA)",
            ["ps1|superbike2000"] = "EA Sports Superbike 2000 (USA)",
            ["psp|blackrockshooter"] = "Black Rock Shooter - The Game (USA)",
            ["psp|championshipmanager"] = "Entraineur 2006, L' - Championship Manager (France)",
            ["psp|codedarms"] = "Coded Arms - Contagion (Japan) (v1.02)",
            ["psp|hotshotstennis"] = "Hot Shots Tennis - Get a Grip (USA) (v1.01)",
            ["psp|tombraiderlegend"] = "Lara Croft Tomb Raider - Legend (USA) (v1.02)",
            ["sega32x|afterburner"] = "After Burner Complete (Japan, USA) (En)",
            ["sg1000|chuugakuhisshuueibunpou"] = "Chuugaku Hisshuu Eibunpou - Chuugaku 1-Nen (Japan) (SC-3000) (Program)",
            ["sg1000|chuugakuhisshuueisakubun"] = "Chuugaku Hisshuu Eisakubun - Chuugaku 1-Nen (Japan) (SC-3000) (Program)",
            ["sg1000|chuugakuhisshuueitango"] = "Chuugaku Hisshuu Eitango - Chuugaku 1-Nen (Japan) (SC-3000) (Program)",
            ["sg1000|pitfallii"] = "Pitfall II - The Lost Caverns (Japan)",
            ["sg1000|tanoshiisansuu"] = "Tanoshii Sansuu - Shougaku 4-Nen Ge (Japan) (SC-3000) (Program)",
            ["sms|f16fighter"] = "F-16 Fighting Falcon _ F-16 Fighter _ F16 Falcon Fighter (USA, Europe, Brazil) (En)",
            ["sms|lorettanoshouzou"] = "Loretta no Shouzou - Sherlock Holmes (Japan)",
            ["sms|shadowdancer"] = "Shadow Dancer - The Secret of Shinobi _ Shadow Dancer (Europe, Brazil) (En)",
            ["sms|shootinggallery"] = "Shooting Gallery _ Shooting G. (USA, Europe, Brazil) (En)",
            ["sms|tennisace"] = "Tennis Ace _ Super Tennis (Europe, Brazil) (En)",
            ["sms|tvcolosso"] = "Aventuras da TV Colosso, As (Brazil)",
            ["sms|worldcupitalia90"] = "World Cup Italia '90 _ Super Futebol II (Europe, Brazil) (En)",
            ["sms|worldsoccer"] = "World Soccer _ Great Soccer _ Super Futebol (World)",
            ["snes|bazoemahousekai"] = "Ancient Magic - Bazoe! Mahou Sekai (Japan)",
            ["snes|dragonquestvi"] = "Dragon Quest VI - Maboroshi no Daichi (Japan)",
            ["snes|kingofrallythe"] = "King of Rally, The - Paris-Moscow-Beijing (Japan)",
            ["snes|nbaprobasketballbullsvsblazers"] = "NBA Pro Basketball - Bulls vs Blazers and the NBA Playoffs (Japan)",
            ["snes|scoobydoo"] = "Scooby-Doo Mystery (USA)",
            ["snes|simcity2000"] = "SimCity 2000 - The Ultimate City Simulator (Japan)",
            ["snes|sinkorswim"] = "S.O.S - Sink or Swim (Europe)",
            ["wsc|digimonanodetamercathodetamer"] = "Digimon - Anode Tamer & Cathode Tamer - Veedramon Version (2001)(Bandai)(HK)",
            ["n64|1080teneightysnowboarding"] = "1080 Snowboarding (Japan, USA) (En,Ja)",
            ["n64|kobebryantsnbacourtside"] = "Kobe Bryant in NBA Courtside (USA)",
            ["n64|quake64"] = "Quake (USA)",
            // Nintendo DS (2026-07-24 full-collection ingest). The source set is a hand-cleaned collection
            // with no region tags, so several cards carry the FRENCH release title while libretro-thumbnails
            // only files the English one — the alias points them at the USA cover of the same game. The rest
            // are ampersand/word spellings ("and" vs "&") and an English retitle (Stafy -> Starfy).
            ["nds|4in1monopolyboggleyahtzeeandbattleship"] = "4 Game Fun Pack - Monopoly + Boggle + Yahtzee + Battleship (USA)",
            ["nds|aliceaupaysdesmerveilles"] = "Alice in Wonderland (USA) (En,Fr,Es) (NDSi Enhanced)",
            ["nds|harvestmoonlarchipeldusoleil"] = "Harvest Moon DS - Sunshine Islands (USA)",
            ["nds|lessims3"] = "Sims 3, The (USA) (En,Fr,Es) (NDSi Enhanced)",
            ["nds|mariosonicauxjeuxolympiquesdhiver"] = "Mario _ Sonic at the Olympic Winter Games (USA)",
            ["nds|marioandluigipartnersintime"] = "Mario _ Luigi - Partners in Time (USA)",
            ["nds|sonicandsegaallstarsracing"] = "Sonic _ SEGA All-Stars Racing (USA) (En,Fr,Es)",
            ["nds|thelegendarystafy"] = "Legendary Starfy, The (USA)",
            // ScummVM (2026-07-25). The repo is named from the same ScummVM game DB we ingest from, so
            // only a handful of cards drift: a numbered-vs-spelled entry ("1st Grade"), a series-number
            // our title adds that the box doesn't ("Freddi Fish 1:" vs "Freddi Fish and the…"), two
            // Crazy Nick's titles the repo files under a shorter/plural name, and the four Simon puzzle
            // minigames, which shipped in ONE box (the Puzzle Pack) — without this the reverse-contiguous
            // rule hands them the base "Simon the Sorcerer" cover, i.e. the wrong game.
            ["scummvm|bigthinkersfirstgrade"] = "Big Thinkers 1st Grade",
            ["scummvm|crazynickssoftwarepicksleisuresuitlarryscasino"] = "Crazy Nick's Picks_ Leisure Suit Larry's Casino",
            ["scummvm|crazynickssoftwarepicksrobinhoodsgameofskillandchance"] = "Crazy Nick's Software Picks_ Robin Hood's Games of Skill and Chance",
            ["scummvm|freddifish1thecaseofthemissingkelpseeds"] = "Freddi Fish and the Case of the Missing Kelp Seeds",
            ["scummvm|simonthesorcererspuzzlepackdemoninmypocket"] = "Simon the Sorcerer Puzzle Pack",
            ["scummvm|simonthesorcererspuzzlepackjumble"] = "Simon the Sorcerer Puzzle Pack",
            ["scummvm|simonthesorcererspuzzlepacknopatience"] = "Simon the Sorcerer Puzzle Pack",
            ["scummvm|simonthesorcererspuzzlepackswampyadventures"] = "Simon the Sorcerer Puzzle Pack",

            // ── Romhacks (2026-07-30) ────────────────────────────────────────────────────────────────
            // A hack's title is its own, so no cover database matches it: libretro has no entry, IGDB
            // has no id, and the SteamGridDB title search misses on names this generic ("Chaos Edition",
            // "On-Foot Mode Unlocked"). Point each at its BASE GAME's official box, which is the closest
            // honest art and is what the card would otherwise show a placeholder for. Every target below
            // was HEAD-checked against the libretro-thumbnails repo before being added — an unverified
            // guess here just re-breaks the card silently.
            ["n64|mario64randomizer"] = "Super Mario 64 (USA)",
            ["n64|chaosedition"] = "Super Mario 64 (USA)",
            ["n64|fourswordsarenaedition"] = "Legend of Zelda, The - Ocarina of Time (USA)",
            ["n64|ootrandomizerseedlibrary2026"] = "Legend of Zelda, The - Ocarina of Time (USA)",
            ["n64|onfootmodeunlocked"] = "Star Fox 64 (USA)",
            ["nes|supermario3mix"] = "Super Mario Bros. 3 (USA)",
            ["nds|ctgpnitro"] = "Mario Kart DS (USA) (En,Fr,De,Es,It)",
            ["snes|zeroproject"] = "Mega Man X3 (USA)",
            // ps1's first romhack (2026-07-31). Without the alias the fallback chain reached past
            // libretro to a franchise-title search and returned the NES "Castlevania" box — confidently
            // wrong art on a PS1 card, the exact failure this table exists to prevent.
            ["ps1|castlevaniarondoofthenight"] = "Castlevania - Symphony of the Night (USA)",
            // Fifth romhack round (2026-07-31). Only the hacks that NO cover DB can reach get a base-game
            // alias — SteamGridDB carries real hack-specific covers for Waluigi's Taco Stand, Conker's High
            // Rule Tail, EarthBound Halloween Hack and Pokemon Kart 64, and an alias here would preempt them.
            // These three need it, and two of them need it defensively: SteamGridDB's prefix rule matches
            // "TMNT Shredder's Re-Revenge" to the unrelated 2007 "TMNT", so without an alias the card would
            // get a confidently-wrong box.
            ["genesis|tmntshreddersrerevenge"] = "Streets of Rage 2 (USA)",
            ["n64|zeldasbirthday"] = "Legend of Zelda, The - Ocarina of Time (USA)",
            ["nes|wilfordbrimleybattle"] = "River City Ransom (USA)",
            // "NES Deadpool" was left unaliased in the 2026-07-30 round because its base game was unknown.
            // The RHDN entry (hack 4723) names it: a total conversion of Ninja Gaiden. Aliased 2026-07-31 —
            // this was the only romhack card still serving a placeholder that HAS an honest base-game box.
            // (The other blank, "Titanic English Translation", stays blank on purpose: its base is an
            // unlicensed Shenzhen Nanjing cart that no cover database carries.)
            ["nes|nesdeadpool"] = "Ninja Gaiden (USA)",
            // Deliberately NOT aliased: the two Zelda "Redux" cards (renamed 2026-07-31 so they stop
            // collapsing into the stock game's card). A base-game alias was added here and then removed the
            // same day: with no alias the cascade reaches SteamGridDB, which carries authentic fan-made
            // covers with "REDUX" on the spine for both — strictly better art than the stock box this table
            // would have pinned them to. Same rule as the round-5 romhacks: an alias PREEMPTS the cascade,
            // so only alias what SteamGridDB genuinely misses.
        };

        /// <summary>The aliased libretro filename for a card, or null.</summary>
        public static string? For(string system, string title) =>
            Map.TryGetValue(system + "|" + ArcadeBoxArtIndex.Normalize(title), out var name) ? name : null;
    }
}
