// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieTheater.Books.Db;

#nullable disable

namespace MovieTheater.Books.Db.Migrations.Legs
{
    [DbContext(typeof(BooksLegsDb))]
    partial class BooksLegsDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("MovieTheater.Books.Db.BarcodeScan", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<int>("PagesScanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("ScannedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.ToTable("BarcodeScan", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.CvVolumeRaw", b =>
                {
                    b.Property<int>("CvVolumeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharactersJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConceptsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamsJson")
                        .HasColumnType("TEXT");

                    b.HasKey("CvVolumeId");

                    b.ToTable("CvVolumeRaw", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.GcdIssue", b =>
                {
                    b.Property<int>("GcdIssueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GcdSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isbn")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeriesYearBegan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoryGenres")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidIsbn")
                        .HasColumnType("TEXT");

                    b.Property<string>("VariantName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VariantOfId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GcdIssueId");

                    b.HasIndex("Barcode");

                    b.HasIndex("GcdSeriesId");

                    b.HasIndex("ValidIsbn");

                    b.ToTable("GcdIssue", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.GcdSeries", b =>
                {
                    b.Property<int>("GcdSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Binding")
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasBarcode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("HasIsbn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT");

                    b.Property<string>("SortName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("YearBegan")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("YearEnded")
                        .HasColumnType("INTEGER");

                    b.HasKey("GcdSeriesId");

                    b.ToTable("GcdSeries", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.LinkCandidates", b =>
                {
                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CandidatesJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Scope", "Key", "Provider");

                    b.ToTable("LinkCandidates", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.LocgComicRaw", b =>
                {
                    b.Property<int>("LocgComicId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CommunityRating")
                        .HasColumnType("REAL");

                    b.Property<string>("CoverDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DistributorSku")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstimatedValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Isbn")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LocgSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RatingCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ScrapedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StoryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoryIdsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Upc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("LocgComicId");

                    b.ToTable("LocgComicRaw", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.LocgContainment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChapterTitle")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ContainedLocgComicId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContainerLocgComicId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("ScrapedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContainedLocgComicId");

                    b.HasIndex("ContainerLocgComicId", "ContainedLocgComicId")
                        .IsUnique();

                    b.ToTable("LocgContainment", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.LocgCreatorRaw", b =>
                {
                    b.Property<int>("LocgComicId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PeopleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.HasKey("LocgComicId", "Ordinal");

                    b.ToTable("LocgCreatorRaw", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.LocgSeries", b =>
                {
                    b.Property<int>("LocgSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT");

                    b.Property<int?>("YearBegin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("YearEnd")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YearText")
                        .HasColumnType("TEXT");

                    b.HasKey("LocgSeriesId");

                    b.ToTable("LocgSeries", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.LocgSeriesInference", b =>
                {
                    b.Property<int>("GcdSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocgSeriesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Support")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("GcdSeriesId");

                    b.ToTable("LocgSeriesInference", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.MarvelIssue", b =>
                {
                    b.Property<int>("MarvelIssueId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MarvelSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ScrapedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .HasColumnType("TEXT");

                    b.HasKey("MarvelIssueId");

                    b.ToTable("MarvelIssue", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.MarvelSeries", b =>
                {
                    b.Property<int>("MarvelSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ScrapedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .HasColumnType("TEXT");

                    b.Property<int?>("YearEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("YearStart")
                        .HasColumnType("INTEGER");

                    b.HasKey("MarvelSeriesId");

                    b.ToTable("MarvelSeries", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.MarvelSeriesLink", b =>
                {
                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MarvelSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchedKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("SeriesId");

                    b.ToTable("MarvelSeriesLink", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.MuSeriesRaw", b =>
                {
                    b.Property<long>("MuSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoriesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("GenresJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawJson")
                        .HasColumnType("TEXT");

                    b.HasKey("MuSeriesId");

                    b.ToTable("MuSeriesRaw", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.OlSeriesInference", b =>
                {
                    b.Property<int>("GcdSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IsbnSupport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("OlWorkKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesString")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectsJson")
                        .HasColumnType("TEXT");

                    b.HasKey("GcdSeriesId");

                    b.ToTable("OlSeriesInference", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.OpenLibraryEdition", b =>
                {
                    b.Property<string>("Isbn")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OlEditionKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("OlWorkKey")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Pages")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhysicalFormat")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publishers")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesString")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Isbn");

                    b.HasIndex("OlWorkKey");

                    b.ToTable("OpenLibraryEdition", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.OpenLibraryWork", b =>
                {
                    b.Property<string>("WorkKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("EditionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesString")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("WorkKey");

                    b.ToTable("OpenLibraryWork", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.ProviderResponseCache", b =>
                {
                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Provider", "RequestKey");

                    b.ToTable("ProviderResponseCache", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
