// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieTheater.Books.Db;

#nullable disable

namespace MovieTheater.Books.Db.Migrations.Hot
{
    [DbContext(typeof(BooksDb))]
    partial class BooksDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("MovieTheater.Books.Db.BarneyProg", b =>
                {
                    b.Property<int>("ProgNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ScrapedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("StripsJson")
                        .HasColumnType("TEXT");

                    b.HasKey("ProgNo");

                    b.ToTable("BarneyProg", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.BookDetail", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isbn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SeriesIndex")
                        .HasColumnType("REAL");

                    b.Property<string>("SeriesName")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex("Isbn");

                    b.HasIndex("SeriesName", "SeriesIndex");

                    b.ToTable("BookDetail", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.CollectedEditionSpan", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<bool>("Contiguous")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditionTitle")
                        .HasColumnType("TEXT");

                    b.Property<double?>("IssueEnd")
                        .HasColumnType("REAL");

                    b.Property<double?>("IssueStart")
                        .HasColumnType("REAL");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderRef")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId", "Source");

                    b.HasIndex("SeriesId");

                    b.ToTable("CollectedEditionSpan", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.CollectionNode", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContainsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int?>("ParentItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpanEnd")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpanLabel")
                        .HasColumnType("TEXT");

                    b.Property<int>("SpanSource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int?>("SpanStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("ItemId");

                    b.HasIndex("ContainsCount")
                        .IsDescending();

                    b.HasIndex("ParentItemId");

                    b.HasIndex("SeriesId");

                    b.ToTable("CollectionNode", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.ComicDetail", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Confidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("EventName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderSeries")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FolderYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Format")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("FormatRaw")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCollection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("IssueNo")
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueSource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("IssueTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParseNotes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ParsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParsedSeriesKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT");

                    b.Property<int>("PublisherSource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("SeriesSource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int?>("VolumeNo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearSource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("ItemId");

                    b.HasIndex("EventName");

                    b.HasIndex("ParsedSeriesKey");

                    b.HasIndex("Year");

                    b.ToTable("ComicDetail", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.ComicEmbedded", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgeRating")
                        .HasColumnType("TEXT");

                    b.Property<string>("AltNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("AltSeries")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("BlackAndWhite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Characters")
                        .HasColumnType("TEXT");

                    b.Property<string>("Colorist")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverArtist")
                        .HasColumnType("TEXT");

                    b.Property<string>("Editor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Identifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Imprint")
                        .HasColumnType("TEXT");

                    b.Property<string>("Inker")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("Letterer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Locations")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manga")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pencillers")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Series")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoryArc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("Teams")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Volume")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Web")
                        .HasColumnType("TEXT");

                    b.Property<string>("Writers")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.ToTable("ComicEmbedded", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.CvIssue", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Deck")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteDetailUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VolumeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VolumeId");

                    b.ToTable("CvIssue", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.CvVolume", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CountOfIssues")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Deck")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublisherName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteDetailUrl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CvVolume", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.CvdbResolution", b =>
                {
                    b.Property<string>("CvdbTag")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ComicvineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("CvdbTag");

                    b.ToTable("CvdbResolution", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.DerivedTable", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputFingerprint")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastRebuiltAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RebuildJob")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RowCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Name");

                    b.ToTable("DerivedTable", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.DuplicateGroup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Evidence")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Relationship")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewState")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SuggestedKeeperItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DuplicateGroup", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.DuplicateMember", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DuplicateGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SoleFileInFolder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("DuplicateGroupId");

                    b.HasIndex("ItemId");

                    b.ToTable("DuplicateMember", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.ExternalWork", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Authors")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FirstPublishYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InfoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isbn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ProviderKey")
                        .IsUnique();

                    b.ToTable("ExternalWork", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.Folder", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Depth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("DescendantItemCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("DirectChildCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("FolderModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasIcon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("IndexedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RootId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int?>("TopFolderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName");

                    b.HasIndex("ParentId");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("RootId");

                    b.HasIndex("TopFolderId");

                    b.ToTable("Folder", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.GroupMark", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupKey")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WantToRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("UserId", "GroupType", "GroupKey");

                    b.HasIndex("UserId", "GroupType", "WantToRead");

                    b.ToTable("GroupMark", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.Insight", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<int>("Confidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int?>("Maturity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Recognized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("ReviewFlag")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKey")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectKind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Synopsis")
                        .HasColumnType("TEXT");

                    b.Property<int?>("YearBegin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("YearEnd")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubjectKind", "Maturity")
                        .HasFilter("\"IsCurrent\" = 1");

                    b.HasIndex("SubjectKind", "SubjectId", "IsCurrent");

                    b.ToTable("Insight", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.InsightTag", b =>
                {
                    b.Property<int>("InsightId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("InsightId", "Category", "Value");

                    b.ToTable("InsightTag", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.Item", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CalibreBookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContainerFormat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<double?>("CoverAspect")
                        .HasColumnType("REAL");

                    b.Property<string>("Extension")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FileModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<int>("FolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("IndexedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExcluded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("KeepInDirectory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("Kind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("NormalizedTitle")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedCreatorsCsv")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResolvedDatePrecision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int?>("ResolvedMonth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResolvedPublisher")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResolvedRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResolvedSeries")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResolvedSynopsisSource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("ResolvedTagsCsv")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedTitle")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResolvedYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RootId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int?>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TopFolderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CalibreBookId")
                        .IsUnique();

                    b.HasIndex("FolderId");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("PublisherId");

                    b.HasIndex("RootId");

                    b.HasIndex("TopFolderId");

                    b.HasIndex("SeriesId", "Id");

                    b.HasIndex("Kind", "IndexedAt", "Id")
                        .IsDescending(false, true, false);

                    b.HasIndex("Kind", "NormalizedTitle", "Id");

                    b.HasIndex("Kind", "ResolvedPublisher", "Id");

                    b.HasIndex("Kind", "ResolvedRating", "Id")
                        .IsDescending(false, true, false);

                    b.HasIndex("Kind", "ResolvedSeries", "Id");

                    b.HasIndex("Kind", "ResolvedYear", "IndexedAt", "Id")
                        .IsDescending(false, true, true, false);

                    b.ToTable("Item", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.ItemCredit", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderPersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId", "Source", "Ordinal");

                    b.HasIndex("Role", "NormalizedName", "ItemId");

                    b.ToTable("ItemCredit", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.ItemProviderLink", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Applied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("AttemptedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quality")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("SecondaryKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int?>("StoredTopScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId", "Provider");

                    b.HasIndex("Provider", "ProviderKey");

                    b.HasIndex("Provider", "Status");

                    b.ToTable("ItemProviderLink", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.ItemSignature", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentFingerprint")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CoverPHash")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PageSignature")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignaturesComputedFor")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex("ContentFingerprint");

                    b.HasIndex("CoverPHash");

                    b.ToTable("ItemSignature", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.ItemState", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BrokenCheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrokenReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverDimsComputedFor")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CoverHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CoverWidth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExcludedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExclusionReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBroken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ThumbnailCheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailError")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.ToTable("ItemState", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.ItemTag", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId", "Category", "Value", "Source");

                    b.HasIndex("Category", "Value", "ItemId");

                    b.ToTable("ItemTag", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.KidSafeTag", b =>
                {
                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppliesTo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Category", "Tag");

                    b.ToTable("KidSafeTag", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.KnownIdentity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("KidsStyle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaturityCeiling")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("KnownIdentity", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.LibraryRoot", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsCalibre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("Kind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("LibraryRoot", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.LocgComic", b =>
                {
                    b.Property<int>("LocgComicId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CommunityRating")
                        .HasColumnType("REAL");

                    b.Property<string>("CoverDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Isbn")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LocgSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RatingCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ScrapedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StoryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Upc")
                        .HasColumnType("TEXT");

                    b.HasKey("LocgComicId");

                    b.ToTable("LocgComic", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.MigrationProgress", b =>
                {
                    b.Property<string>("Stage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cursor")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Processed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Total")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Stage");

                    b.ToTable("MigrationProgress", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.MuSeries", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BayesianRating")
                        .HasColumnType("REAL");

                    b.Property<bool>("Completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ScrapedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MuSeries", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.MuSeriesLink", b =>
                {
                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .HasColumnType("TEXT");

                    b.Property<long?>("MuSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("SeriesId");

                    b.ToTable("MuSeriesLink", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Publisher", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.Rating", b =>
                {
                    b.Property<int>("TargetKind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOverride")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawScale")
                        .HasColumnType("TEXT");

                    b.Property<double?>("RawValue")
                        .HasColumnType("REAL");

                    b.Property<int?>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("TargetKind", "TargetId", "Source");

                    b.ToTable("Rating", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.ReadingOrderEntry", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ComputedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Confidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReadCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("ReadDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReadDatePrecision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int?>("ReadIndex")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ReadNumber")
                        .HasColumnType("REAL");

                    b.Property<double?>("ReadNumberSuffix")
                        .HasColumnType("REAL");

                    b.Property<int?>("ReadTier")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("ItemId");

                    b.HasIndex("SeriesId", "ReadIndex");

                    b.ToTable("ReadingOrderEntry", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.ScanRun", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Added")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Changed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemsSeen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Kind")
                        .HasColumnType("TEXT");

                    b.Property<int>("Removed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int?>("RootId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScanRun", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.Series", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CvVolumeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayNameOverride")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExternalWorkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Franchise")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOngoing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("IssueCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<long?>("MuSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParsedKey")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResolvedRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResolvedSynopsisSource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int?>("YearEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("YearStart")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalKey")
                        .IsUnique();

                    b.HasIndex("Franchise");

                    b.HasIndex("ParsedKey");

                    b.HasIndex("Name", "Id");

                    b.HasIndex("ResolvedRating", "Id")
                        .IsDescending(true, false);

                    b.ToTable("Series", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.SeriesAlias", b =>
                {
                    b.Property<string>("ParsedKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("ParsedKey");

                    b.HasIndex("SeriesId");

                    b.ToTable("SeriesAlias", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.SeriesInferenceDecision", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .HasColumnType("TEXT");

                    b.Property<string>("Class")
                        .HasColumnType("TEXT");

                    b.Property<string>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecidedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .HasColumnType("TEXT");

                    b.Property<string>("UndoJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("State", "Class");

                    b.ToTable("SeriesInferenceDecision", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.SeriesKeyLink", b =>
                {
                    b.Property<string>("ParsedKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("AttemptedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProviderKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int?>("StoredTopScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("ParsedKey", "Provider");

                    b.HasIndex("Status");

                    b.HasIndex("Provider", "ProviderKey");

                    b.ToTable("SeriesKeyLink", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.SeriesMatchReview", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecidedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Scope", "Key")
                        .IsUnique();

                    b.ToTable("SeriesMatchReview", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.SeriesMerge", b =>
                {
                    b.Property<int>("OldSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("MergedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NewSeriesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OldSeriesId");

                    b.ToTable("SeriesMerge", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.SeriesTag", b =>
                {
                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("SeriesId", "Category", "Value", "Source");

                    b.HasIndex("Category", "Value", "SeriesId");

                    b.ToTable("SeriesTag", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.SystemState", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("SystemState", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.TagAlias", b =>
                {
                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("AliasTag")
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalTag")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.HasKey("Category", "AliasTag");

                    b.ToTable("TagAlias", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.UserItemState", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Favorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("HiddenFromHistory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("LastPage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<double?>("LastScrollPercent")
                        .HasColumnType("REAL");

                    b.Property<int?>("LastSpineItemIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WantToRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("UserId", "ItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId", "UpdatedAt")
                        .IsDescending(false, true);

                    b.HasIndex("UserId", "WantToRead");

                    b.ToTable("UserItemState", (string)null);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.BookDetail", b =>
                {
                    b.HasOne("MovieTheater.Books.Db.Item", null)
                        .WithOne("Book")
                        .HasForeignKey("MovieTheater.Books.Db.BookDetail", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieTheater.Books.Db.CollectedEditionSpan", b =>
                {
                    b.HasOne("MovieTheater.Books.Db.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieTheater.Books.Db.CollectionNode", b =>
                {
                    b.HasOne("MovieTheater.Books.Db.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovieTheater.Books.Db.Item", null)
                        .WithMany()
                        .HasForeignKey("ParentItemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MovieTheater.Books.Db.ComicDetail", b =>
                {
                    b.HasOne("MovieTheater.Books.Db.Item", null)
                        .WithOne("Comic")
                        .HasForeignKey("MovieTheater.Books.Db.ComicDetail", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieTheater.Books.Db.ComicEmbedded", b =>
                {
                    b.HasOne("MovieTheater.Books.Db.Item", null)
                        .WithOne("Embedded")
                        .HasForeignKey("MovieTheater.Books.Db.ComicEmbedded", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieTheater.Books.Db.DuplicateMember", b =>
                {
                    b.HasOne("MovieTheater.Books.Db.DuplicateGroup", null)
                        .WithMany()
                        .HasForeignKey("DuplicateGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovieTheater.Books.Db.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieTheater.Books.Db.Folder", b =>
                {
                    b.HasOne("MovieTheater.Books.Db.Folder", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MovieTheater.Books.Db.LibraryRoot", null)
                        .WithMany()
                        .HasForeignKey("RootId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieTheater.Books.Db.InsightTag", b =>
                {
                    b.HasOne("MovieTheater.Books.Db.Insight", null)
                        .WithMany()
                        .HasForeignKey("InsightId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieTheater.Books.Db.Item", b =>
                {
                    b.HasOne("MovieTheater.Books.Db.Folder", "Folder")
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovieTheater.Books.Db.Publisher", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MovieTheater.Books.Db.LibraryRoot", null)
                        .WithMany()
                        .HasForeignKey("RootId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovieTheater.Books.Db.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Folder");

                    b.Navigation("Publisher");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("MovieTheater.Books.Db.ItemCredit", b =>
                {
                    b.HasOne("MovieTheater.Books.Db.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieTheater.Books.Db.ItemProviderLink", b =>
                {
                    b.HasOne("MovieTheater.Books.Db.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieTheater.Books.Db.ItemSignature", b =>
                {
                    b.HasOne("MovieTheater.Books.Db.Item", null)
                        .WithOne("Signature")
                        .HasForeignKey("MovieTheater.Books.Db.ItemSignature", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieTheater.Books.Db.ItemState", b =>
                {
                    b.HasOne("MovieTheater.Books.Db.Item", null)
                        .WithOne("State")
                        .HasForeignKey("MovieTheater.Books.Db.ItemState", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieTheater.Books.Db.ItemTag", b =>
                {
                    b.HasOne("MovieTheater.Books.Db.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieTheater.Books.Db.MuSeriesLink", b =>
                {
                    b.HasOne("MovieTheater.Books.Db.Series", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieTheater.Books.Db.ReadingOrderEntry", b =>
                {
                    b.HasOne("MovieTheater.Books.Db.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieTheater.Books.Db.SeriesAlias", b =>
                {
                    b.HasOne("MovieTheater.Books.Db.Series", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieTheater.Books.Db.SeriesTag", b =>
                {
                    b.HasOne("MovieTheater.Books.Db.Series", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieTheater.Books.Db.UserItemState", b =>
                {
                    b.HasOne("MovieTheater.Books.Db.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieTheater.Books.Db.Item", b =>
                {
                    b.Navigation("Book");

                    b.Navigation("Comic");

                    b.Navigation("Embedded");

                    b.Navigation("Signature");

                    b.Navigation("State");
                });
#pragma warning restore 612, 618
        }
    }
}
