//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTheater.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class movieDB : DbContext
    {
        public movieDB()
            : base("name=movieDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Movie> Movies { get; set; }
        public virtual DbSet<MoviePoster> MoviePosters { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Viewing> Viewings { get; set; }
        public virtual DbSet<MovieCollection> MovieCollections { get; set; }
        public virtual DbSet<UserMovies> UserMovies { get; set; }
    }
}
