//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTheater.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMovies
    {
        public string Title { get; set; }
        public string SimpleTitle { get; set; }
        public string Rating { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string Runtime { get; set; }
        public string Genre { get; set; }
        public string Director { get; set; }
        public string Writer { get; set; }
        public string Actors { get; set; }
        public string Plot { get; set; }
        public byte[] Poster { get; set; }
        public string PosterLink { get; set; }
        public Nullable<decimal> imdbRating { get; set; }
        public string imdbID { get; set; }
        public Nullable<int> tomatoRating { get; set; }
        public int id { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ViewingType { get; set; }
        public string isWatched { get; set; }
        public string isWatchlist { get; set; }
        public Nullable<int> MovieID { get; set; }
    }
}
