//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTheater.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viewing
    {
        public Nullable<int> MovieID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ViewingType { get; set; }
        public int ViewingID { get; set; }
        public string ViewingData { get; set; }
        public string ServerData { get; set; }
    }
}
