// <auto-generated> by scripts/books/gen/gen_entities.py from docs/books/v2-mapping.json — do not edit by hand.
#nullable enable
using System;

namespace MovieTheater.Books.Db
{
    // books-legs.db — offline warehouse; no FK crosses the file boundary.
    /// <summary>Every LOCG row incl. the 73k stubs and the columns nothing reads at runtime; the containment reduction reads this</summary>
    public sealed class LocgComicRaw
    {
        public int LocgComicId { get; set; }
        public int? LocgSeriesId { get; set; }
        public string? SeriesName { get; set; }
        public string? Title { get; set; }
        public string? IssueNumber { get; set; }
        public string? Format { get; set; }
        public string? ReleaseDate { get; set; }
        public string? CoverDate { get; set; }
        public int? PageCount { get; set; }
        public string? Description { get; set; }
        public double? CommunityRating { get; set; }
        public int? RatingCount { get; set; }
        public bool IsKey { get; set; }
        public string? KeyType { get; set; }
        public string? KeyReason { get; set; }
        public string? Isbn { get; set; }
        public string? Upc { get; set; }
        public string? DistributorSku { get; set; }
        public string? CoverPrice { get; set; }
        public string? EstimatedValue { get; set; }
        public string? CoverUrl { get; set; }
        public string? Url { get; set; }
        public int? StoryCount { get; set; }
        public string? StoryIdsJson { get; set; }
        public DateTime? ScrapedAt { get; set; }
    }

    /// <summary>CreatorsJson normalized for ALL LOCG rows (the hot ItemCredit(Source=Locg) is the matched subset)</summary>
    public sealed class LocgCreatorRaw
    {
        public int LocgComicId { get; set; }
        public int Ordinal { get; set; }
        public string? Role { get; set; }
        public string? Name { get; set; }
        public string? PeopleId { get; set; }
    }

    /// <summary>391k forward/reverse containment edges - input to books-locg-containment only</summary>
    public sealed class LocgContainment
    {
        public int Id { get; set; }
        public int? ContainerLocgComicId { get; set; }
        public int? ContainedLocgComicId { get; set; }
        public string? ChapterTitle { get; set; }
        public int Ordinal { get; set; }
        public string? Source { get; set; }
        public int? StoryId { get; set; }
        public DateTime? ScrapedAt { get; set; }
    }

    /// <summary>LOCG series (python leg)</summary>
    public sealed class LocgSeries
    {
        public int LocgSeriesId { get; set; }
        public string? Name { get; set; }
        public string? Publisher { get; set; }
        public int? YearBegin { get; set; }
        public int? YearEnd { get; set; }
        public string? YearText { get; set; }
        public int IssueCount { get; set; }
        public DateTime? ImportedAt { get; set; }
    }

    /// <summary>GCD-series -> LOCG-series inference</summary>
    public sealed class LocgSeriesInference
    {
        public int GcdSeriesId { get; set; }
        public string? LocgSeriesId { get; set; }
        public string? SeriesName { get; set; }
        public int Support { get; set; }
        public DateTime? ImportedAt { get; set; }
    }

    /// <summary>GCD issues (the story-genre fold reads them into ItemTag(Source=Gcd))</summary>
    public sealed class GcdIssue
    {
        public int GcdIssueId { get; set; }
        public int? GcdSeriesId { get; set; }
        public string? SeriesName { get; set; }
        public int? SeriesYearBegan { get; set; }
        public string? Number { get; set; }
        public string? Title { get; set; }
        public string? KeyDate { get; set; }
        public string? PublicationDate { get; set; }
        public string? ValidIsbn { get; set; }
        public string? Isbn { get; set; }
        public string? Barcode { get; set; }
        public int? PageCount { get; set; }
        public string? Price { get; set; }
        public string? Publisher { get; set; }
        public string? Format { get; set; }
        public int? VariantOfId { get; set; }
        public string? VariantName { get; set; }
        public DateTime? ImportedAt { get; set; }
        public string? StoryGenres { get; set; }
    }

    /// <summary>GCD series</summary>
    public sealed class GcdSeries
    {
        public int GcdSeriesId { get; set; }
        public string? Name { get; set; }
        public string? SortName { get; set; }
        public int? YearBegan { get; set; }
        public int? YearEnded { get; set; }
        public string? Publisher { get; set; }
        public string? Format { get; set; }
        public int IssueCount { get; set; }
        public bool HasIsbn { get; set; }
        public bool HasBarcode { get; set; }
        public string? Binding { get; set; }
        public string? Notes { get; set; }
        public DateTime? ImportedAt { get; set; }
    }

    /// <summary>ISBN-keyed OL editions</summary>
    public sealed class OpenLibraryEdition
    {
        public string Isbn { get; set; } = "";
        public string? Title { get; set; }
        public string? Subtitle { get; set; }
        public string? AuthorsJson { get; set; }
        public string? Publishers { get; set; }
        public string? PublishDate { get; set; }
        public int? Pages { get; set; }
        public string? SubjectsJson { get; set; }
        public string? CoverUrl { get; set; }
        public string? OlEditionKey { get; set; }
        public string? OlWorkKey { get; set; }
        public string? SeriesString { get; set; }
        public string? PhysicalFormat { get; set; }
        public DateTime? ImportedAt { get; set; }
    }

    /// <summary>OL works</summary>
    public sealed class OpenLibraryWork
    {
        public string WorkKey { get; set; } = "";
        public string? Title { get; set; }
        public string? SubjectsJson { get; set; }
        public string? SeriesString { get; set; }
        public int EditionCount { get; set; }
        public DateTime? ImportedAt { get; set; }
    }

    /// <summary>GCD-series -> OL-work inference</summary>
    public sealed class OlSeriesInference
    {
        public int GcdSeriesId { get; set; }
        public string? OlWorkKey { get; set; }
        public string? SeriesString { get; set; }
        public string? SubjectsJson { get; set; }
        public int IsbnSupport { get; set; }
        public DateTime? ImportedAt { get; set; }
    }

    /// <summary>Marvel identity leg</summary>
    public sealed class MarvelSeries
    {
        public int MarvelSeriesId { get; set; }
        public string? Slug { get; set; }
        public string? Name { get; set; }
        public int? YearStart { get; set; }
        public int? YearEnd { get; set; }
        public DateTime? ScrapedAt { get; set; }
    }

    /// <summary>Marvel identity leg</summary>
    public sealed class MarvelIssue
    {
        public int MarvelIssueId { get; set; }
        public int? MarvelSeriesId { get; set; }
        public string? Number { get; set; }
        public string? Slug { get; set; }
        public DateTime? ScrapedAt { get; set; }
    }

    /// <summary>Marvel series match (128 rows)</summary>
    public sealed class MarvelSeriesLink
    {
        public int SeriesId { get; set; }
        public int? MarvelSeriesId { get; set; }
        public string? Status { get; set; }
        public double? Confidence { get; set; }
        public string? MatchedKey { get; set; }
        public DateTime? CreatedAt { get; set; }
    }

    /// <summary>Barcode sweep results</summary>
    public sealed class BarcodeScan
    {
        public int ItemId { get; set; }
        public string? CodesJson { get; set; }
        public int PagesScanned { get; set; }
        public string? Error { get; set; }
        public DateTime? ScannedAt { get; set; }
    }

    /// <summary>Cache-first API bodies (ComicVine today)</summary>
    public sealed class ProviderResponseCache
    {
        public Provider Provider { get; set; }
        public string RequestKey { get; set; } = "";
        public string? ResponseJson { get; set; }
        public DateTime? FetchedAt { get; set; }
    }

    /// <summary>CandidatesJson for links that are NOT Pending/Multiple (audit trail; the hot links keep candidates only while a decision is open)</summary>
    public sealed class LinkCandidates
    {
        public SubjectKind Scope { get; set; }
        public string Key { get; set; } = "";
        public Provider Provider { get; set; }
        public string? CandidatesJson { get; set; }
    }

    /// <summary>MangaUpdates raw payload + JSON lists</summary>
    public sealed class MuSeriesRaw
    {
        public long MuSeriesId { get; set; }
        public string? GenresJson { get; set; }
        public string? CategoriesJson { get; set; }
        public string? RawJson { get; set; }
    }

    /// <summary>ComicVine volume JSON lists (concepts/characters/locations/objects/teams) - all '[]' today</summary>
    public sealed class CvVolumeRaw
    {
        public int CvVolumeId { get; set; }
        public string? ConceptsJson { get; set; }
        public string? CharactersJson { get; set; }
        public string? LocationsJson { get; set; }
        public string? ObjectsJson { get; set; }
        public string? TeamsJson { get; set; }
    }

}
