name: MovieTheater Integration Tests
on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  docker-build-api:
    runs-on: movietheater
    steps:
      - uses: actions/checkout@v4
      - run: echo "$MOVIETHEATER_APPSETTINGS_JSON" > src/MovieTheater/appsettings.Production.json
        env:
          MOVIETHEATER_APPSETTINGS_JSON: ${{ secrets.MOVIETHEATER_APPSETTINGS_JSON }}
      - run: cd docker && bash build-api.sh

  docker-build-ui:
    runs-on: movietheater
    steps:
      - uses: actions/checkout@v4
      - run: cd docker && bash build-ui.sh
