name: MovieTheater Prod Deploy
on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: movietheater
    outputs:
      image_tag: ${{ steps.tag.outputs.tag }}
    steps:
      - id: tag
        run: echo "tag=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

  docker-build-api:
    needs: [setup]
    runs-on: movietheater
    env:
      REGISTRY: registry.local:32500
      IMAGE_TAG: ${{ needs.setup.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "$MOVIETHEATER_APPSETTINGS_JSON" > src/MovieTheater/appsettings.Production.json
        env:
          MOVIETHEATER_APPSETTINGS_JSON: ${{ secrets.MOVIETHEATER_APPSETTINGS_JSON }}
      - run: cd docker && bash build-api.sh
      - run: docker push $REGISTRY/movietheater-api:$IMAGE_TAG

  docker-build-ui:
    needs: [setup]
    runs-on: movietheater
    env:
      REGISTRY: registry.local:32500
      IMAGE_TAG: ${{ needs.setup.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4
      - run: cd docker && bash build-ui.sh
      - run: docker push $REGISTRY/movietheater-ui:$IMAGE_TAG
